// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	model "rocketvault/model"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockKeyRepositoryInterface is an autogenerated mock type for the KeyRepositoryInterface type
type MockKeyRepositoryInterface struct {
	mock.Mock
}

type MockKeyRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKeyRepositoryInterface) EXPECT() *MockKeyRepositoryInterface_Expecter {
	return &MockKeyRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, key
func (_m *MockKeyRepositoryInterface) Create(ctx context.Context, key *model.Key) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Key) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKeyRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockKeyRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - key *model.Key
func (_e *MockKeyRepositoryInterface_Expecter) Create(ctx interface{}, key interface{}) *MockKeyRepositoryInterface_Create_Call {
	return &MockKeyRepositoryInterface_Create_Call{Call: _e.mock.On("Create", ctx, key)}
}

func (_c *MockKeyRepositoryInterface_Create_Call) Run(run func(ctx context.Context, key *model.Key)) *MockKeyRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Key))
	})
	return _c
}

func (_c *MockKeyRepositoryInterface_Create_Call) Return(_a0 error) *MockKeyRepositoryInterface_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKeyRepositoryInterface_Create_Call) RunAndReturn(run func(context.Context, *model.Key) error) *MockKeyRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateVersion provides a mock function with given fields: ctx, keyID, version, value
func (_m *MockKeyRepositoryInterface) CreateVersion(ctx context.Context, keyID uuid.UUID, version int, value string) error {
	ret := _m.Called(ctx, keyID, version, value)

	if len(ret) == 0 {
		panic("no return value specified for CreateVersion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, string) error); ok {
		r0 = rf(ctx, keyID, version, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKeyRepositoryInterface_CreateVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateVersion'
type MockKeyRepositoryInterface_CreateVersion_Call struct {
	*mock.Call
}

// CreateVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID uuid.UUID
//   - version int
//   - value string
func (_e *MockKeyRepositoryInterface_Expecter) CreateVersion(ctx interface{}, keyID interface{}, version interface{}, value interface{}) *MockKeyRepositoryInterface_CreateVersion_Call {
	return &MockKeyRepositoryInterface_CreateVersion_Call{Call: _e.mock.On("CreateVersion", ctx, keyID, version, value)}
}

func (_c *MockKeyRepositoryInterface_CreateVersion_Call) Run(run func(ctx context.Context, keyID uuid.UUID, version int, value string)) *MockKeyRepositoryInterface_CreateVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(string))
	})
	return _c
}

func (_c *MockKeyRepositoryInterface_CreateVersion_Call) Return(_a0 error) *MockKeyRepositoryInterface_CreateVersion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKeyRepositoryInterface_CreateVersion_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, string) error) *MockKeyRepositoryInterface_CreateVersion_Call {
	_c.Call.Return(run)
	return _c
}

// CurrentVersion provides a mock function with given fields: ctx, keyID
func (_m *MockKeyRepositoryInterface) CurrentVersion(ctx context.Context, keyID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, keyID)

	if len(ret) == 0 {
		panic("no return value specified for CurrentVersion")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return rf(ctx, keyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = rf(ctx, keyID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, keyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeyRepositoryInterface_CurrentVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CurrentVersion'
type MockKeyRepositoryInterface_CurrentVersion_Call struct {
	*mock.Call
}

// CurrentVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID uuid.UUID
func (_e *MockKeyRepositoryInterface_Expecter) CurrentVersion(ctx interface{}, keyID interface{}) *MockKeyRepositoryInterface_CurrentVersion_Call {
	return &MockKeyRepositoryInterface_CurrentVersion_Call{Call: _e.mock.On("CurrentVersion", ctx, keyID)}
}

func (_c *MockKeyRepositoryInterface_CurrentVersion_Call) Run(run func(ctx context.Context, keyID uuid.UUID)) *MockKeyRepositoryInterface_CurrentVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockKeyRepositoryInterface_CurrentVersion_Call) Return(_a0 int, _a1 error) *MockKeyRepositoryInterface_CurrentVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeyRepositoryInterface_CurrentVersion_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int, error)) *MockKeyRepositoryInterface_CurrentVersion_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockKeyRepositoryInterface) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKeyRepositoryInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockKeyRepositoryInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockKeyRepositoryInterface_Expecter) Delete(ctx interface{}, id interface{}) *MockKeyRepositoryInterface_Delete_Call {
	return &MockKeyRepositoryInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockKeyRepositoryInterface_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockKeyRepositoryInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockKeyRepositoryInterface_Delete_Call) Return(_a0 error) *MockKeyRepositoryInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKeyRepositoryInterface_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockKeyRepositoryInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetVersion provides a mock function with given fields: ctx, keyID, version
func (_m *MockKeyRepositoryInterface) GetVersion(ctx context.Context, keyID uuid.UUID, version int) (*model.KeyVersion, error) {
	ret := _m.Called(ctx, keyID, version)

	if len(ret) == 0 {
		panic("no return value specified for GetVersion")
	}

	var r0 *model.KeyVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) (*model.KeyVersion, error)); ok {
		return rf(ctx, keyID, version)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) *model.KeyVersion); ok {
		r0 = rf(ctx, keyID, version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.KeyVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) error); ok {
		r1 = rf(ctx, keyID, version)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeyRepositoryInterface_GetVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVersion'
type MockKeyRepositoryInterface_GetVersion_Call struct {
	*mock.Call
}

// GetVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID uuid.UUID
//   - version int
func (_e *MockKeyRepositoryInterface_Expecter) GetVersion(ctx interface{}, keyID interface{}, version interface{}) *MockKeyRepositoryInterface_GetVersion_Call {
	return &MockKeyRepositoryInterface_GetVersion_Call{Call: _e.mock.On("GetVersion", ctx, keyID, version)}
}

func (_c *MockKeyRepositoryInterface_GetVersion_Call) Run(run func(ctx context.Context, keyID uuid.UUID, version int)) *MockKeyRepositoryInterface_GetVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int))
	})
	return _c
}

func (_c *MockKeyRepositoryInterface_GetVersion_Call) Return(_a0 *model.KeyVersion, _a1 error) *MockKeyRepositoryInterface_GetVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeyRepositoryInterface_GetVersion_Call) RunAndReturn(run func(context.Context, uuid.UUID, int) (*model.KeyVersion, error)) *MockKeyRepositoryInterface_GetVersion_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, scope, filter
func (_m *MockKeyRepositoryInterface) List(ctx context.Context, scope model.Scope, filter model.KeyFilter) ([]model.Key, error) {
	ret := _m.Called(ctx, scope, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Key
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Scope, model.KeyFilter) ([]model.Key, error)); ok {
		return rf(ctx, scope, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Scope, model.KeyFilter) []model.Key); ok {
		r0 = rf(ctx, scope, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Key)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Scope, model.KeyFilter) error); ok {
		r1 = rf(ctx, scope, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeyRepositoryInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockKeyRepositoryInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - scope model.Scope
//   - filter model.KeyFilter
func (_e *MockKeyRepositoryInterface_Expecter) List(ctx interface{}, scope interface{}, filter interface{}) *MockKeyRepositoryInterface_List_Call {
	return &MockKeyRepositoryInterface_List_Call{Call: _e.mock.On("List", ctx, scope, filter)}
}

func (_c *MockKeyRepositoryInterface_List_Call) Run(run func(ctx context.Context, scope model.Scope, filter model.KeyFilter)) *MockKeyRepositoryInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Scope), args[2].(model.KeyFilter))
	})
	return _c
}

func (_c *MockKeyRepositoryInterface_List_Call) Return(_a0 []model.Key, _a1 error) *MockKeyRepositoryInterface_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeyRepositoryInterface_List_Call) RunAndReturn(run func(context.Context, model.Scope, model.KeyFilter) ([]model.Key, error)) *MockKeyRepositoryInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListVersionRecords provides a mock function with given fields: ctx, keyID
func (_m *MockKeyRepositoryInterface) ListVersionRecords(ctx context.Context, keyID uuid.UUID) ([]model.KeyVersionRecord, error) {
	ret := _m.Called(ctx, keyID)

	if len(ret) == 0 {
		panic("no return value specified for ListVersionRecords")
	}

	var r0 []model.KeyVersionRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.KeyVersionRecord, error)); ok {
		return rf(ctx, keyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.KeyVersionRecord); ok {
		r0 = rf(ctx, keyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.KeyVersionRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, keyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeyRepositoryInterface_ListVersionRecords_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListVersionRecords'
type MockKeyRepositoryInterface_ListVersionRecords_Call struct {
	*mock.Call
}

// ListVersionRecords is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID uuid.UUID
func (_e *MockKeyRepositoryInterface_Expecter) ListVersionRecords(ctx interface{}, keyID interface{}) *MockKeyRepositoryInterface_ListVersionRecords_Call {
	return &MockKeyRepositoryInterface_ListVersionRecords_Call{Call: _e.mock.On("ListVersionRecords", ctx, keyID)}
}

func (_c *MockKeyRepositoryInterface_ListVersionRecords_Call) Run(run func(ctx context.Context, keyID uuid.UUID)) *MockKeyRepositoryInterface_ListVersionRecords_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockKeyRepositoryInterface_ListVersionRecords_Call) Return(_a0 []model.KeyVersionRecord, _a1 error) *MockKeyRepositoryInterface_ListVersionRecords_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeyRepositoryInterface_ListVersionRecords_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]model.KeyVersionRecord, error)) *MockKeyRepositoryInterface_ListVersionRecords_Call {
	_c.Call.Return(run)
	return _c
}

// ListVersions provides a mock function with given fields: ctx, keyID
func (_m *MockKeyRepositoryInterface) ListVersions(ctx context.Context, keyID uuid.UUID) ([]model.KeyVersion, error) {
	ret := _m.Called(ctx, keyID)

	if len(ret) == 0 {
		panic("no return value specified for ListVersions")
	}

	var r0 []model.KeyVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.KeyVersion, error)); ok {
		return rf(ctx, keyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.KeyVersion); ok {
		r0 = rf(ctx, keyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.KeyVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, keyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeyRepositoryInterface_ListVersions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListVersions'
type MockKeyRepositoryInterface_ListVersions_Call struct {
	*mock.Call
}

// ListVersions is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID uuid.UUID
func (_e *MockKeyRepositoryInterface_Expecter) ListVersions(ctx interface{}, keyID interface{}) *MockKeyRepositoryInterface_ListVersions_Call {
	return &MockKeyRepositoryInterface_ListVersions_Call{Call: _e.mock.On("ListVersions", ctx, keyID)}
}

func (_c *MockKeyRepositoryInterface_ListVersions_Call) Run(run func(ctx context.Context, keyID uuid.UUID)) *MockKeyRepositoryInterface_ListVersions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockKeyRepositoryInterface_ListVersions_Call) Return(_a0 []model.KeyVersion, _a1 error) *MockKeyRepositoryInterface_ListVersions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeyRepositoryInterface_ListVersions_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]model.KeyVersion, error)) *MockKeyRepositoryInterface_ListVersions_Call {
	_c.Call.Return(run)
	return _c
}

// PurgeKey provides a mock function with given fields: ctx, id
func (_m *MockKeyRepositoryInterface) PurgeKey(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for PurgeKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKeyRepositoryInterface_PurgeKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurgeKey'
type MockKeyRepositoryInterface_PurgeKey_Call struct {
	*mock.Call
}

// PurgeKey is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockKeyRepositoryInterface_Expecter) PurgeKey(ctx interface{}, id interface{}) *MockKeyRepositoryInterface_PurgeKey_Call {
	return &MockKeyRepositoryInterface_PurgeKey_Call{Call: _e.mock.On("PurgeKey", ctx, id)}
}

func (_c *MockKeyRepositoryInterface_PurgeKey_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockKeyRepositoryInterface_PurgeKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockKeyRepositoryInterface_PurgeKey_Call) Return(_a0 error) *MockKeyRepositoryInterface_PurgeKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKeyRepositoryInterface_PurgeKey_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockKeyRepositoryInterface_PurgeKey_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function with given fields: ctx, id, scope
func (_m *MockKeyRepositoryInterface) Read(ctx context.Context, id uuid.UUID, scope model.Scope) (*model.Key, error) {
	ret := _m.Called(ctx, id, scope)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 *model.Key
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) (*model.Key, error)); ok {
		return rf(ctx, id, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) *model.Key); ok {
		r0 = rf(ctx, id, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Key)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.Scope) error); ok {
		r1 = rf(ctx, id, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeyRepositoryInterface_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockKeyRepositoryInterface_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - scope model.Scope
func (_e *MockKeyRepositoryInterface_Expecter) Read(ctx interface{}, id interface{}, scope interface{}) *MockKeyRepositoryInterface_Read_Call {
	return &MockKeyRepositoryInterface_Read_Call{Call: _e.mock.On("Read", ctx, id, scope)}
}

func (_c *MockKeyRepositoryInterface_Read_Call) Run(run func(ctx context.Context, id uuid.UUID, scope model.Scope)) *MockKeyRepositoryInterface_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.Scope))
	})
	return _c
}

func (_c *MockKeyRepositoryInterface_Read_Call) Return(_a0 *model.Key, _a1 error) *MockKeyRepositoryInterface_Read_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeyRepositoryInterface_Read_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.Scope) (*model.Key, error)) *MockKeyRepositoryInterface_Read_Call {
	_c.Call.Return(run)
	return _c
}

// ReadDeletedScoped provides a mock function with given fields: ctx, id, scope
func (_m *MockKeyRepositoryInterface) ReadDeletedScoped(ctx context.Context, id uuid.UUID, scope model.Scope) (*model.Key, error) {
	ret := _m.Called(ctx, id, scope)

	if len(ret) == 0 {
		panic("no return value specified for ReadDeletedScoped")
	}

	var r0 *model.Key
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) (*model.Key, error)); ok {
		return rf(ctx, id, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) *model.Key); ok {
		r0 = rf(ctx, id, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Key)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.Scope) error); ok {
		r1 = rf(ctx, id, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeyRepositoryInterface_ReadDeletedScoped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadDeletedScoped'
type MockKeyRepositoryInterface_ReadDeletedScoped_Call struct {
	*mock.Call
}

// ReadDeletedScoped is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - scope model.Scope
func (_e *MockKeyRepositoryInterface_Expecter) ReadDeletedScoped(ctx interface{}, id interface{}, scope interface{}) *MockKeyRepositoryInterface_ReadDeletedScoped_Call {
	return &MockKeyRepositoryInterface_ReadDeletedScoped_Call{Call: _e.mock.On("ReadDeletedScoped", ctx, id, scope)}
}

func (_c *MockKeyRepositoryInterface_ReadDeletedScoped_Call) Run(run func(ctx context.Context, id uuid.UUID, scope model.Scope)) *MockKeyRepositoryInterface_ReadDeletedScoped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.Scope))
	})
	return _c
}

func (_c *MockKeyRepositoryInterface_ReadDeletedScoped_Call) Return(_a0 *model.Key, _a1 error) *MockKeyRepositoryInterface_ReadDeletedScoped_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeyRepositoryInterface_ReadDeletedScoped_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.Scope) (*model.Key, error)) *MockKeyRepositoryInterface_ReadDeletedScoped_Call {
	_c.Call.Return(run)
	return _c
}

// ReadVersionValue provides a mock function with given fields: ctx, keyID, version
func (_m *MockKeyRepositoryInterface) ReadVersionValue(ctx context.Context, keyID uuid.UUID, version int) (string, error) {
	ret := _m.Called(ctx, keyID, version)

	if len(ret) == 0 {
		panic("no return value specified for ReadVersionValue")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) (string, error)); ok {
		return rf(ctx, keyID, version)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) string); ok {
		r0 = rf(ctx, keyID, version)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) error); ok {
		r1 = rf(ctx, keyID, version)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeyRepositoryInterface_ReadVersionValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadVersionValue'
type MockKeyRepositoryInterface_ReadVersionValue_Call struct {
	*mock.Call
}

// ReadVersionValue is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID uuid.UUID
//   - version int
func (_e *MockKeyRepositoryInterface_Expecter) ReadVersionValue(ctx interface{}, keyID interface{}, version interface{}) *MockKeyRepositoryInterface_ReadVersionValue_Call {
	return &MockKeyRepositoryInterface_ReadVersionValue_Call{Call: _e.mock.On("ReadVersionValue", ctx, keyID, version)}
}

func (_c *MockKeyRepositoryInterface_ReadVersionValue_Call) Run(run func(ctx context.Context, keyID uuid.UUID, version int)) *MockKeyRepositoryInterface_ReadVersionValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int))
	})
	return _c
}

func (_c *MockKeyRepositoryInterface_ReadVersionValue_Call) Return(_a0 string, _a1 error) *MockKeyRepositoryInterface_ReadVersionValue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeyRepositoryInterface_ReadVersionValue_Call) RunAndReturn(run func(context.Context, uuid.UUID, int) (string, error)) *MockKeyRepositoryInterface_ReadVersionValue_Call {
	_c.Call.Return(run)
	return _c
}

// RecoverKey provides a mock function with given fields: ctx, id
func (_m *MockKeyRepositoryInterface) RecoverKey(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RecoverKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKeyRepositoryInterface_RecoverKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecoverKey'
type MockKeyRepositoryInterface_RecoverKey_Call struct {
	*mock.Call
}

// RecoverKey is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockKeyRepositoryInterface_Expecter) RecoverKey(ctx interface{}, id interface{}) *MockKeyRepositoryInterface_RecoverKey_Call {
	return &MockKeyRepositoryInterface_RecoverKey_Call{Call: _e.mock.On("RecoverKey", ctx, id)}
}

func (_c *MockKeyRepositoryInterface_RecoverKey_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockKeyRepositoryInterface_RecoverKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockKeyRepositoryInterface_RecoverKey_Call) Return(_a0 error) *MockKeyRepositoryInterface_RecoverKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKeyRepositoryInterface_RecoverKey_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockKeyRepositoryInterface_RecoverKey_Call {
	_c.Call.Return(run)
	return _c
}

// RecoverVaultContents provides a mock function with given fields: ctx, vaultID, deletedAt
func (_m *MockKeyRepositoryInterface) RecoverVaultContents(ctx context.Context, vaultID uuid.UUID, deletedAt time.Time) error {
	ret := _m.Called(ctx, vaultID, deletedAt)

	if len(ret) == 0 {
		panic("no return value specified for RecoverVaultContents")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = rf(ctx, vaultID, deletedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKeyRepositoryInterface_RecoverVaultContents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecoverVaultContents'
type MockKeyRepositoryInterface_RecoverVaultContents_Call struct {
	*mock.Call
}

// RecoverVaultContents is a helper method to define mock.On call
//   - ctx context.Context
//   - vaultID uuid.UUID
//   - deletedAt time.Time
func (_e *MockKeyRepositoryInterface_Expecter) RecoverVaultContents(ctx interface{}, vaultID interface{}, deletedAt interface{}) *MockKeyRepositoryInterface_RecoverVaultContents_Call {
	return &MockKeyRepositoryInterface_RecoverVaultContents_Call{Call: _e.mock.On("RecoverVaultContents", ctx, vaultID, deletedAt)}
}

func (_c *MockKeyRepositoryInterface_RecoverVaultContents_Call) Run(run func(ctx context.Context, vaultID uuid.UUID, deletedAt time.Time)) *MockKeyRepositoryInterface_RecoverVaultContents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockKeyRepositoryInterface_RecoverVaultContents_Call) Return(_a0 error) *MockKeyRepositoryInterface_RecoverVaultContents_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKeyRepositoryInterface_RecoverVaultContents_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) error) *MockKeyRepositoryInterface_RecoverVaultContents_Call {
	_c.Call.Return(run)
	return _c
}

// SetPurgeProtection provides a mock function with given fields: ctx, id, enabled
func (_m *MockKeyRepositoryInterface) SetPurgeProtection(ctx context.Context, id uuid.UUID, enabled bool) error {
	ret := _m.Called(ctx, id, enabled)

	if len(ret) == 0 {
		panic("no return value specified for SetPurgeProtection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) error); ok {
		r0 = rf(ctx, id, enabled)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKeyRepositoryInterface_SetPurgeProtection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPurgeProtection'
type MockKeyRepositoryInterface_SetPurgeProtection_Call struct {
	*mock.Call
}

// SetPurgeProtection is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - enabled bool
func (_e *MockKeyRepositoryInterface_Expecter) SetPurgeProtection(ctx interface{}, id interface{}, enabled interface{}) *MockKeyRepositoryInterface_SetPurgeProtection_Call {
	return &MockKeyRepositoryInterface_SetPurgeProtection_Call{Call: _e.mock.On("SetPurgeProtection", ctx, id, enabled)}
}

func (_c *MockKeyRepositoryInterface_SetPurgeProtection_Call) Run(run func(ctx context.Context, id uuid.UUID, enabled bool)) *MockKeyRepositoryInterface_SetPurgeProtection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(bool))
	})
	return _c
}

func (_c *MockKeyRepositoryInterface_SetPurgeProtection_Call) Return(_a0 error) *MockKeyRepositoryInterface_SetPurgeProtection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKeyRepositoryInterface_SetPurgeProtection_Call) RunAndReturn(run func(context.Context, uuid.UUID, bool) error) *MockKeyRepositoryInterface_SetPurgeProtection_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDelete provides a mock function with given fields: ctx, id
func (_m *MockKeyRepositoryInterface) SoftDelete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKeyRepositoryInterface_SoftDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDelete'
type MockKeyRepositoryInterface_SoftDelete_Call struct {
	*mock.Call
}

// SoftDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockKeyRepositoryInterface_Expecter) SoftDelete(ctx interface{}, id interface{}) *MockKeyRepositoryInterface_SoftDelete_Call {
	return &MockKeyRepositoryInterface_SoftDelete_Call{Call: _e.mock.On("SoftDelete", ctx, id)}
}

func (_c *MockKeyRepositoryInterface_SoftDelete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockKeyRepositoryInterface_SoftDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockKeyRepositoryInterface_SoftDelete_Call) Return(_a0 error) *MockKeyRepositoryInterface_SoftDelete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKeyRepositoryInterface_SoftDelete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockKeyRepositoryInterface_SoftDelete_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDeleteVaultContents provides a mock function with given fields: ctx, vaultID, deletedAt
func (_m *MockKeyRepositoryInterface) SoftDeleteVaultContents(ctx context.Context, vaultID uuid.UUID, deletedAt time.Time) error {
	ret := _m.Called(ctx, vaultID, deletedAt)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteVaultContents")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = rf(ctx, vaultID, deletedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKeyRepositoryInterface_SoftDeleteVaultContents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDeleteVaultContents'
type MockKeyRepositoryInterface_SoftDeleteVaultContents_Call struct {
	*mock.Call
}

// SoftDeleteVaultContents is a helper method to define mock.On call
//   - ctx context.Context
//   - vaultID uuid.UUID
//   - deletedAt time.Time
func (_e *MockKeyRepositoryInterface_Expecter) SoftDeleteVaultContents(ctx interface{}, vaultID interface{}, deletedAt interface{}) *MockKeyRepositoryInterface_SoftDeleteVaultContents_Call {
	return &MockKeyRepositoryInterface_SoftDeleteVaultContents_Call{Call: _e.mock.On("SoftDeleteVaultContents", ctx, vaultID, deletedAt)}
}

func (_c *MockKeyRepositoryInterface_SoftDeleteVaultContents_Call) Run(run func(ctx context.Context, vaultID uuid.UUID, deletedAt time.Time)) *MockKeyRepositoryInterface_SoftDeleteVaultContents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockKeyRepositoryInterface_SoftDeleteVaultContents_Call) Return(_a0 error) *MockKeyRepositoryInterface_SoftDeleteVaultContents_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKeyRepositoryInterface_SoftDeleteVaultContents_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) error) *MockKeyRepositoryInterface_SoftDeleteVaultContents_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, key, scope
func (_m *MockKeyRepositoryInterface) Update(ctx context.Context, key *model.Key, scope model.Scope) error {
	ret := _m.Called(ctx, key, scope)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Key, model.Scope) error); ok {
		r0 = rf(ctx, key, scope)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKeyRepositoryInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockKeyRepositoryInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - key *model.Key
//   - scope model.Scope
func (_e *MockKeyRepositoryInterface_Expecter) Update(ctx interface{}, key interface{}, scope interface{}) *MockKeyRepositoryInterface_Update_Call {
	return &MockKeyRepositoryInterface_Update_Call{Call: _e.mock.On("Update", ctx, key, scope)}
}

func (_c *MockKeyRepositoryInterface_Update_Call) Run(run func(ctx context.Context, key *model.Key, scope model.Scope)) *MockKeyRepositoryInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Key), args[2].(model.Scope))
	})
	return _c
}

func (_c *MockKeyRepositoryInterface_Update_Call) Return(_a0 error) *MockKeyRepositoryInterface_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKeyRepositoryInterface_Update_Call) RunAndReturn(run func(context.Context, *model.Key, model.Scope) error) *MockKeyRepositoryInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRevocationStatus provides a mock function with given fields: ctx, id, revoked
func (_m *MockKeyRepositoryInterface) UpdateRevocationStatus(ctx context.Context, id uuid.UUID, revoked bool) error {
	ret := _m.Called(ctx, id, revoked)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRevocationStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) error); ok {
		r0 = rf(ctx, id, revoked)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKeyRepositoryInterface_UpdateRevocationStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRevocationStatus'
type MockKeyRepositoryInterface_UpdateRevocationStatus_Call struct {
	*mock.Call
}

// UpdateRevocationStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - revoked bool
func (_e *MockKeyRepositoryInterface_Expecter) UpdateRevocationStatus(ctx interface{}, id interface{}, revoked interface{}) *MockKeyRepositoryInterface_UpdateRevocationStatus_Call {
	return &MockKeyRepositoryInterface_UpdateRevocationStatus_Call{Call: _e.mock.On("UpdateRevocationStatus", ctx, id, revoked)}
}

func (_c *MockKeyRepositoryInterface_UpdateRevocationStatus_Call) Run(run func(ctx context.Context, id uuid.UUID, revoked bool)) *MockKeyRepositoryInterface_UpdateRevocationStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(bool))
	})
	return _c
}

func (_c *MockKeyRepositoryInterface_UpdateRevocationStatus_Call) Return(_a0 error) *MockKeyRepositoryInterface_UpdateRevocationStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKeyRepositoryInterface_UpdateRevocationStatus_Call) RunAndReturn(run func(context.Context, uuid.UUID, bool) error) *MockKeyRepositoryInterface_UpdateRevocationStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockKeyRepositoryInterface creates a new instance of MockKeyRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKeyRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKeyRepositoryInterface {
	mock := &MockKeyRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
