// Package users provides user management services for the password manager.
// It handles user creation, updates, and management workflows while
// coordinating with authentication services and repositories.
package users

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/sirupsen/logrus"

	"rocketvault/common"
	"rocketvault/internal/logging"
	"rocketvault/internal/repositories"
	authService "rocketvault/internal/services/auth"
	"rocketvault/model"
)

// CreateUserRequest represents a request to create a new user.
type CreateUserRequest struct {
	Username    string
	Password    string
	Roles       []string
	CallerRoles []string // Must include model.RoleAdmin.
}

// FindOrCreateExternalUserRequest identifies an externally-authenticated
// principal.
type FindOrCreateExternalUserRequest struct {
	Provider          string // e.g. model.AuthProviderOIDC
	Subject           string // The provider's stable subject (sub claim)
	PreferredUsername string // Best-effort display name; disambiguated on collision
}

// CreateUserResult represents the result of creating a new user.
type CreateUserResult struct {
	UserID     uuid.UUID
	Username   string
	Roles      []string
	TOTPSecret string
	CreatedAt  time.Time
}

// UpdateUserRequest represents a request to update an existing user.
type UpdateUserRequest struct {
	UserID      uuid.UUID
	CallerID    uuid.UUID // Unused today (pre-existing dead field) -- left as-is.
	CallerRoles []string  // Must include model.RoleAdmin for any Roles change.
	Username    *string
	Password    *string
	Roles       []string // nil means no change; non-nil (even empty) is a validation error.
}

// UpdateUserResult reports side effects of UpdateUser that the caller must show the user.
type UpdateUserResult struct {
	// TOTPEnrollmentURL is the otpauth:// URL of a TOTP secret generated by
	// this call. It is empty unless the account had no secret before.
	// It is a credential: never log it, audit it, or persist it elsewhere.
	TOTPEnrollmentURL string
}

// guardSystemUser rejects any mutation targeting the reserved row at
// model.SystemUserID. That row is not an account: it exists so the `keys`
// table's FOREIGN KEY (user_id) REFERENCES users(id) is satisfiable for
// internally-generated resources, currently SelfPKIProvider's own JWT
// signing key (see model.SystemUserID's doc comment and known-bugs.md B60).
//
// Deleting it cascades that signing key away on Postgres, so every
// outstanding token fails its `kid` lookup and the instance silently
// re-keys on next boot; on SQLite it leaves the key dangling and reopens
// B60. Updating it can hand the reserved row a real password hash and role.
// Neither DELETE /api/v1/users/{id} (admin plus "not your own account") nor
// `rocketvault users delete <id>` excluded this id, and the id is the
// well-known uuid.Nil, so both are reachable by any admin. The repository's
// List and bootstrap-count queries already hide this row; this closes the
// write side.
func guardSystemUser(userID uuid.UUID, verb string) error {
	if userID.String() == model.SystemUserID {
		return fmt.Errorf("the reserved system user cannot be %s", verb)
	}
	return nil
}

// UserService handles user management operations.
// It orchestrates user creation and updates by coordinating
// with authentication services and user repositories.
type UserService interface {
	CreateUser(ctx context.Context, req CreateUserRequest) (*CreateUserResult, error)
	UpdateUser(ctx context.Context, req UpdateUserRequest) (*UpdateUserResult, error)
	GetUser(ctx context.Context, userID uuid.UUID) (*model.User, error)
	GetUserByUsername(ctx context.Context, username string) (*model.User, error)
	// FindOrCreateExternalUser looks up a user by (provider, subject),
	// creating one with the lowest-privilege default role if none exists.
	// Used by the OIDC callback after ID token verification — this method
	// performs no credential check itself.
	FindOrCreateExternalUser(ctx context.Context, req FindOrCreateExternalUserRequest) (*model.User, error)
	ListUsers(ctx context.Context) ([]model.User, error)
	DeleteUser(ctx context.Context, userID uuid.UUID) error
	ValidateBootstrapToken(ctx context.Context, token string) (bool, error)
	InvalidateBootstrapToken(ctx context.Context, token string) error
}

// userService implements UserService by coordinating authentication
// services and user repository operations.
type userService struct {
	userRepo        repositories.UserRepositoryInterface
	passwordService authService.PasswordService
	totpService     authService.TOTPService
	logger          *logging.Logger
}

// UserServiceConfig holds the dependencies for user service.
type UserServiceConfig struct {
	UserRepository  repositories.UserRepositoryInterface
	PasswordService authService.PasswordService
	TOTPService     authService.TOTPService
	Logger          *logging.Logger
}

// NewUserService creates a new UserService with the provided dependencies.
// It orchestrates user management operations by coordinating different services.
//
// Parameters:
//
//	config: Configuration containing all required dependencies.
//
// Returns:
//
//	A UserService implementation for user management operations.
func NewUserService(config UserServiceConfig) UserService {
	return &userService{
		userRepo:        config.UserRepository,
		passwordService: config.PasswordService,
		totpService:     config.TOTPService,
		logger:          config.Logger,
	}
}

// CreateUser creates a new user with the provided information.
// It orchestrates password hashing, TOTP secret generation,
// and user storage while maintaining proper separation of concerns.
//
// Parameters:
//
//	ctx: The context for the operation.
//	req: The user creation request with username, password, and roles.
//
// Returns:
//
//	The created user information including TOTP setup details, or an error if creation fails.
func (s *userService) CreateUser(ctx context.Context, req CreateUserRequest) (*CreateUserResult, error) {
	if !common.HasAnyRole(req.CallerRoles, model.RoleAdmin) {
		return nil, fmt.Errorf("forbidden: caller must have admin role to create users")
	}

	seen := map[string]bool{}
	var roles []string
	for _, r := range req.Roles {
		// HasAnyRole (Plan 03) requires pre-trimmed input -- it does no
		// trimming itself, unlike the comma-string helper it replaced. Trim
		// here, at the write boundary, or a role stored with stray
		// whitespace silently fails every future authorization check.
		r = strings.TrimSpace(r)
		if r == "" || seen[r] {
			continue
		}
		if !model.IsValidRole(r) {
			return nil, fmt.Errorf("invalid role: %s", r)
		}
		seen[r] = true
		roles = append(roles, r)
	}
	if len(roles) == 0 {
		return nil, fmt.Errorf("invalid role: at least one role is required")
	}

	logrus.WithFields(logrus.Fields{
		"username": req.Username,
		"roles":    roles,
	}).Info("Creating new user")

	hashedPassword, err := s.passwordService.HashPassword(req.Password)
	if err != nil {
		s.logger.LogAuditError("", "create_user", "failed", "Failed to hash password", err)
		return nil, fmt.Errorf("failed to prepare user: %w", err)
	}

	totpKey, err := s.totpService.GenerateSecret("PasswordManager", req.Username)
	if err != nil {
		s.logger.LogAuditError("", "create_user", "failed", "Failed to generate TOTP secret", err)
		return nil, fmt.Errorf("failed to generate TOTP secret: %w", err)
	}

	userID := uuid.New()
	user := &model.User{
		ID:           userID,
		Username:     req.Username,
		PasswordHash: hashedPassword,
		TOTPSecret:   totpKey.Secret(),
		Roles:        roles,
		CreatedAt:    time.Now(),
	}

	if err := s.userRepo.Create(ctx, user); err != nil {
		s.logger.LogAuditError(userID.String(), "create_user", "failed", "Failed to create user", err)
		return nil, fmt.Errorf("failed to create user: %w", err)
	}

	s.logger.LogAuditInfo(userID.String(), "create_user", "success", fmt.Sprintf("User created: %s", req.Username))

	return &CreateUserResult{
		UserID:     userID,
		Username:   req.Username,
		Roles:      roles,
		TOTPSecret: totpKey.URL(),
		CreatedAt:  user.CreatedAt,
	}, nil
}

// FindOrCreateExternalUser looks up a user by (provider, subject), creating
// one with model.RoleUser (least privilege — an admin must grant vault roles
// separately, exactly as a fresh Entra ID identity has no Key Vault access
// until an RBAC role assignment is made) if none exists.
func (s *userService) FindOrCreateExternalUser(ctx context.Context, req FindOrCreateExternalUserRequest) (*model.User, error) {
	existing, err := s.userRepo.ReadByExternalSubject(ctx, req.Provider, req.Subject)
	if err == nil {
		return existing, nil
	}

	username := req.PreferredUsername
	if username == "" {
		username = req.Subject
	}

	user := &model.User{
		ID:                 uuid.New(),
		Username:           username,
		PasswordHash:       "",
		TOTPSecret:         "",
		Roles:              []string{model.RoleUser},
		AuthProvider:       req.Provider,
		ExternalIDPSubject: req.Subject,
		CreatedAt:          time.Now(),
	}

	if err := s.userRepo.Create(ctx, user); err != nil {
		// Username collision against an existing *local* user (external
		// subjects are already deduplicated by the lookup above) — retry
		// once with a disambiguated username rather than failing the login.
		user.Username = username + "-" + user.ID.String()[:8]
		if err := s.userRepo.Create(ctx, user); err != nil {
			s.logger.LogAuditError("", "find_or_create_external_user", "failed", "Failed to create externally-authenticated user", err)
			return nil, fmt.Errorf("failed to create user: %w", err)
		}
	}

	s.logger.LogAuditInfo(user.ID.String(), "find_or_create_external_user", "success",
		fmt.Sprintf("Created externally-authenticated user: %s (provider=%s)", user.Username, req.Provider))
	return user, nil
}

// UpdateUser updates an existing user with the provided information.
// It handles password hashing if a new password is provided and
// coordinates the update through the repository. Setting a password on an
// account without a TOTP secret also enrolls one.
//
// Parameters:
//
//	ctx: The context for the operation.
//	req: The user update request with optional fields.
//
// Returns:
//
//	A non-nil result on success, carrying the one-time TOTP enrollment URL
//	when a secret was generated, or an error if the update fails.
func (s *userService) UpdateUser(ctx context.Context, req UpdateUserRequest) (*UpdateUserResult, error) {
	if err := guardSystemUser(req.UserID, "updated"); err != nil {
		return nil, err
	}

	// Only admins may change any user's roles -- including their own. This
	// is the self-promotion guard: a non-admin including "admin" (or any
	// role) in req.Roles is rejected here before roles are ever validated
	// or written, regardless of which roles they already hold.
	if req.Roles != nil && !common.HasAnyRole(req.CallerRoles, model.RoleAdmin) {
		return nil, fmt.Errorf("forbidden: only admins can change roles")
	}

	var newRoles []string
	if req.Roles != nil {
		seen := map[string]bool{}
		for _, r := range req.Roles {
			// Same trimming requirement as CreateUser above -- see its comment.
			r = strings.TrimSpace(r)
			if r == "" || seen[r] {
				continue
			}
			if !model.IsValidRole(r) {
				return nil, fmt.Errorf("invalid role: %s", r)
			}
			seen[r] = true
			newRoles = append(newRoles, r)
		}
		if len(newRoles) == 0 {
			return nil, fmt.Errorf("invalid role: at least one role is required")
		}
	}

	logrus.WithField("user_id", req.UserID.String()).Info("Updating user")

	existingUser, err := s.userRepo.Read(ctx, req.UserID)
	if err != nil {
		s.logger.LogAuditError(req.UserID.String(), "update_user", "failed", "User not found", err)
		return nil, fmt.Errorf("user not found: %w", err)
	}

	updatedUser := *existingUser

	if req.Username != nil {
		updatedUser.Username = *req.Username
	}

	var enrollmentURL string
	if req.Password != nil {
		hashedPassword, err := s.passwordService.HashPassword(*req.Password)
		if err != nil {
			s.logger.LogAuditError(req.UserID.String(), "update_user", "failed", "Failed to hash password", err)
			return nil, fmt.Errorf("failed to hash password: %w", err)
		}
		updatedUser.PasswordHash = hashedPassword

		// An account with no TOTP secret, such as one created by OIDC login,
		// gets one now, so the new password is never a single-factor login.
		// An existing secret is kept, or the user's authenticator would stop working.
		// The secret and its URL are never logged or audited.
		if existingUser.TOTPSecret == "" {
			totpKey, err := s.totpService.GenerateSecret("PasswordManager", updatedUser.Username)
			if err != nil {
				s.logger.LogAuditError(req.UserID.String(), "update_user", "failed", "Failed to generate TOTP secret", err)
				return nil, fmt.Errorf("failed to generate TOTP secret: %w", err)
			}
			updatedUser.TOTPSecret = totpKey.Secret()
			enrollmentURL = totpKey.URL()
		}
	}

	if req.Roles != nil {
		updatedUser.Roles = newRoles
	}

	if err := s.userRepo.Update(ctx, &updatedUser); err != nil {
		s.logger.LogAuditError(req.UserID.String(), "update_user", "failed", "Failed to update user", err)
		return nil, fmt.Errorf("failed to update user: %w", err)
	}

	s.logger.LogAuditInfo(req.UserID.String(), "update_user", "success", fmt.Sprintf("User updated: %s", updatedUser.Username))
	logrus.WithFields(logrus.Fields{
		"user_id":  req.UserID.String(),
		"username": updatedUser.Username,
	}).Info("User updated successfully")

	if enrollmentURL != "" {
		s.logger.LogAuditInfo(req.UserID.String(), "enroll_totp", "success", "TOTP secret generated on password set")
	}

	return &UpdateUserResult{TOTPEnrollmentURL: enrollmentURL}, nil
}

// GetUser retrieves a user by ID.
//
// Parameters:
//
//	ctx: The context for the operation.
//	userID: The user's unique identifier.
//
// Returns:
//
//	The user information or an error if not found.
func (s *userService) GetUser(ctx context.Context, userID uuid.UUID) (*model.User, error) {
	return s.userRepo.Read(ctx, userID)
}

// GetUserByUsername retrieves a user by username.
//
// Parameters:
//
//	ctx: The context for the operation.
//	username: The user's username.
//
// Returns:
//
//	The user information or an error if not found.
func (s *userService) GetUserByUsername(ctx context.Context, username string) (*model.User, error) {
	user, err := s.userRepo.ReadByUsername(ctx, username)
	if err != nil {
		return nil, err
	}
	return &user, nil
}

// ListUsers retrieves all users from the system.
//
// Parameters:
//
//	ctx: The context for the operation.
//
// Returns:
//
//	A slice of all users or an error if retrieval fails.
func (s *userService) ListUsers(ctx context.Context) ([]model.User, error) {
	return s.userRepo.List(ctx)
}

// DeleteUser removes a user from the system.
//
// Parameters:
//
//	ctx: The context for the operation.
//	userID: The user's unique identifier.
//
// Returns:
//
//	An error if deletion fails.
func (s *userService) DeleteUser(ctx context.Context, userID uuid.UUID) error {
	if err := guardSystemUser(userID, "deleted"); err != nil {
		return err
	}

	if err := s.userRepo.Delete(ctx, userID); err != nil {
		s.logger.LogAuditError(userID.String(), "delete_user", "failed", "Failed to delete user", err)
		return fmt.Errorf("failed to delete user: %w", err)
	}

	s.logger.LogAuditInfo(userID.String(), "delete_user", "success", "User deleted successfully")
	return nil
}

// ValidateBootstrapToken validates a bootstrap token for initial admin user creation.
//
// Parameters:
//
//	ctx: The context for the operation.
//	token: The bootstrap token to validate.
//
// Returns:
//
//	True if the token is valid, false otherwise, and an error if validation fails.
func (s *userService) ValidateBootstrapToken(ctx context.Context, token string) (bool, error) {
	return s.userRepo.ValidateBootstrapToken(ctx, token)
}

// InvalidateBootstrapToken marks a bootstrap token as used.
//
// Parameters:
//
//	ctx: The context for the operation.
//	token: The bootstrap token to invalidate.
//
// Returns:
//
//	An error if invalidation fails.
func (s *userService) InvalidateBootstrapToken(ctx context.Context, token string) error {
	return s.userRepo.InvalidateBootstrapToken(ctx, token)
}
