// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	keys "rocketvault/internal/services/keys"

	mock "github.com/stretchr/testify/mock"

	model "rocketvault/model"

	uuid "github.com/google/uuid"
)

// MockKeyService is an autogenerated mock type for the KeyService type
type MockKeyService struct {
	mock.Mock
}

type MockKeyService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKeyService) EXPECT() *MockKeyService_Expecter {
	return &MockKeyService_Expecter{mock: &_m.Mock}
}

// CreateECDSAKey provides a mock function with given fields: ctx, req
func (_m *MockKeyService) CreateECDSAKey(ctx context.Context, req keys.CreateKeyRequest) (*keys.CreateKeyResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateECDSAKey")
	}

	var r0 *keys.CreateKeyResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, keys.CreateKeyRequest) (*keys.CreateKeyResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, keys.CreateKeyRequest) *keys.CreateKeyResult); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keys.CreateKeyResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, keys.CreateKeyRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeyService_CreateECDSAKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateECDSAKey'
type MockKeyService_CreateECDSAKey_Call struct {
	*mock.Call
}

// CreateECDSAKey is a helper method to define mock.On call
//   - ctx context.Context
//   - req keys.CreateKeyRequest
func (_e *MockKeyService_Expecter) CreateECDSAKey(ctx interface{}, req interface{}) *MockKeyService_CreateECDSAKey_Call {
	return &MockKeyService_CreateECDSAKey_Call{Call: _e.mock.On("CreateECDSAKey", ctx, req)}
}

func (_c *MockKeyService_CreateECDSAKey_Call) Run(run func(ctx context.Context, req keys.CreateKeyRequest)) *MockKeyService_CreateECDSAKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(keys.CreateKeyRequest))
	})
	return _c
}

func (_c *MockKeyService_CreateECDSAKey_Call) Return(_a0 *keys.CreateKeyResult, _a1 error) *MockKeyService_CreateECDSAKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeyService_CreateECDSAKey_Call) RunAndReturn(run func(context.Context, keys.CreateKeyRequest) (*keys.CreateKeyResult, error)) *MockKeyService_CreateECDSAKey_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOctKey provides a mock function with given fields: ctx, req
func (_m *MockKeyService) CreateOctKey(ctx context.Context, req keys.CreateKeyRequest) (*keys.CreateKeyResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateOctKey")
	}

	var r0 *keys.CreateKeyResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, keys.CreateKeyRequest) (*keys.CreateKeyResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, keys.CreateKeyRequest) *keys.CreateKeyResult); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keys.CreateKeyResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, keys.CreateKeyRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeyService_CreateOctKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOctKey'
type MockKeyService_CreateOctKey_Call struct {
	*mock.Call
}

// CreateOctKey is a helper method to define mock.On call
//   - ctx context.Context
//   - req keys.CreateKeyRequest
func (_e *MockKeyService_Expecter) CreateOctKey(ctx interface{}, req interface{}) *MockKeyService_CreateOctKey_Call {
	return &MockKeyService_CreateOctKey_Call{Call: _e.mock.On("CreateOctKey", ctx, req)}
}

func (_c *MockKeyService_CreateOctKey_Call) Run(run func(ctx context.Context, req keys.CreateKeyRequest)) *MockKeyService_CreateOctKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(keys.CreateKeyRequest))
	})
	return _c
}

func (_c *MockKeyService_CreateOctKey_Call) Return(_a0 *keys.CreateKeyResult, _a1 error) *MockKeyService_CreateOctKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeyService_CreateOctKey_Call) RunAndReturn(run func(context.Context, keys.CreateKeyRequest) (*keys.CreateKeyResult, error)) *MockKeyService_CreateOctKey_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRSAKey provides a mock function with given fields: ctx, req
func (_m *MockKeyService) CreateRSAKey(ctx context.Context, req keys.CreateKeyRequest) (*keys.CreateKeyResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateRSAKey")
	}

	var r0 *keys.CreateKeyResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, keys.CreateKeyRequest) (*keys.CreateKeyResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, keys.CreateKeyRequest) *keys.CreateKeyResult); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keys.CreateKeyResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, keys.CreateKeyRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeyService_CreateRSAKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRSAKey'
type MockKeyService_CreateRSAKey_Call struct {
	*mock.Call
}

// CreateRSAKey is a helper method to define mock.On call
//   - ctx context.Context
//   - req keys.CreateKeyRequest
func (_e *MockKeyService_Expecter) CreateRSAKey(ctx interface{}, req interface{}) *MockKeyService_CreateRSAKey_Call {
	return &MockKeyService_CreateRSAKey_Call{Call: _e.mock.On("CreateRSAKey", ctx, req)}
}

func (_c *MockKeyService_CreateRSAKey_Call) Run(run func(ctx context.Context, req keys.CreateKeyRequest)) *MockKeyService_CreateRSAKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(keys.CreateKeyRequest))
	})
	return _c
}

func (_c *MockKeyService_CreateRSAKey_Call) Return(_a0 *keys.CreateKeyResult, _a1 error) *MockKeyService_CreateRSAKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeyService_CreateRSAKey_Call) RunAndReturn(run func(context.Context, keys.CreateKeyRequest) (*keys.CreateKeyResult, error)) *MockKeyService_CreateRSAKey_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteKey provides a mock function with given fields: ctx, keyID, scope
func (_m *MockKeyService) DeleteKey(ctx context.Context, keyID uuid.UUID, scope model.Scope) (*model.Key, error) {
	ret := _m.Called(ctx, keyID, scope)

	if len(ret) == 0 {
		panic("no return value specified for DeleteKey")
	}

	var r0 *model.Key
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) (*model.Key, error)); ok {
		return rf(ctx, keyID, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) *model.Key); ok {
		r0 = rf(ctx, keyID, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Key)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.Scope) error); ok {
		r1 = rf(ctx, keyID, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeyService_DeleteKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteKey'
type MockKeyService_DeleteKey_Call struct {
	*mock.Call
}

// DeleteKey is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID uuid.UUID
//   - scope model.Scope
func (_e *MockKeyService_Expecter) DeleteKey(ctx interface{}, keyID interface{}, scope interface{}) *MockKeyService_DeleteKey_Call {
	return &MockKeyService_DeleteKey_Call{Call: _e.mock.On("DeleteKey", ctx, keyID, scope)}
}

func (_c *MockKeyService_DeleteKey_Call) Run(run func(ctx context.Context, keyID uuid.UUID, scope model.Scope)) *MockKeyService_DeleteKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.Scope))
	})
	return _c
}

func (_c *MockKeyService_DeleteKey_Call) Return(_a0 *model.Key, _a1 error) *MockKeyService_DeleteKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeyService_DeleteKey_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.Scope) (*model.Key, error)) *MockKeyService_DeleteKey_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteKeyRotationPolicy provides a mock function with given fields: ctx, keyID, scope
func (_m *MockKeyService) DeleteKeyRotationPolicy(ctx context.Context, keyID uuid.UUID, scope model.Scope) error {
	ret := _m.Called(ctx, keyID, scope)

	if len(ret) == 0 {
		panic("no return value specified for DeleteKeyRotationPolicy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) error); ok {
		r0 = rf(ctx, keyID, scope)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKeyService_DeleteKeyRotationPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteKeyRotationPolicy'
type MockKeyService_DeleteKeyRotationPolicy_Call struct {
	*mock.Call
}

// DeleteKeyRotationPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID uuid.UUID
//   - scope model.Scope
func (_e *MockKeyService_Expecter) DeleteKeyRotationPolicy(ctx interface{}, keyID interface{}, scope interface{}) *MockKeyService_DeleteKeyRotationPolicy_Call {
	return &MockKeyService_DeleteKeyRotationPolicy_Call{Call: _e.mock.On("DeleteKeyRotationPolicy", ctx, keyID, scope)}
}

func (_c *MockKeyService_DeleteKeyRotationPolicy_Call) Run(run func(ctx context.Context, keyID uuid.UUID, scope model.Scope)) *MockKeyService_DeleteKeyRotationPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.Scope))
	})
	return _c
}

func (_c *MockKeyService_DeleteKeyRotationPolicy_Call) Return(_a0 error) *MockKeyService_DeleteKeyRotationPolicy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKeyService_DeleteKeyRotationPolicy_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.Scope) error) *MockKeyService_DeleteKeyRotationPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// ExportKey provides a mock function with given fields: ctx, scope, id, version
func (_m *MockKeyService) ExportKey(ctx context.Context, scope model.Scope, id uuid.UUID, version int) (*keys.ExportKeyResult, error) {
	ret := _m.Called(ctx, scope, id, version)

	if len(ret) == 0 {
		panic("no return value specified for ExportKey")
	}

	var r0 *keys.ExportKeyResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Scope, uuid.UUID, int) (*keys.ExportKeyResult, error)); ok {
		return rf(ctx, scope, id, version)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Scope, uuid.UUID, int) *keys.ExportKeyResult); ok {
		r0 = rf(ctx, scope, id, version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keys.ExportKeyResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Scope, uuid.UUID, int) error); ok {
		r1 = rf(ctx, scope, id, version)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeyService_ExportKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportKey'
type MockKeyService_ExportKey_Call struct {
	*mock.Call
}

// ExportKey is a helper method to define mock.On call
//   - ctx context.Context
//   - scope model.Scope
//   - id uuid.UUID
//   - version int
func (_e *MockKeyService_Expecter) ExportKey(ctx interface{}, scope interface{}, id interface{}, version interface{}) *MockKeyService_ExportKey_Call {
	return &MockKeyService_ExportKey_Call{Call: _e.mock.On("ExportKey", ctx, scope, id, version)}
}

func (_c *MockKeyService_ExportKey_Call) Run(run func(ctx context.Context, scope model.Scope, id uuid.UUID, version int)) *MockKeyService_ExportKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Scope), args[2].(uuid.UUID), args[3].(int))
	})
	return _c
}

func (_c *MockKeyService_ExportKey_Call) Return(_a0 *keys.ExportKeyResult, _a1 error) *MockKeyService_ExportKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeyService_ExportKey_Call) RunAndReturn(run func(context.Context, model.Scope, uuid.UUID, int) (*keys.ExportKeyResult, error)) *MockKeyService_ExportKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetKey provides a mock function with given fields: ctx, keyID, scope
func (_m *MockKeyService) GetKey(ctx context.Context, keyID uuid.UUID, scope model.Scope) (*model.Key, error) {
	ret := _m.Called(ctx, keyID, scope)

	if len(ret) == 0 {
		panic("no return value specified for GetKey")
	}

	var r0 *model.Key
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) (*model.Key, error)); ok {
		return rf(ctx, keyID, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) *model.Key); ok {
		r0 = rf(ctx, keyID, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Key)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.Scope) error); ok {
		r1 = rf(ctx, keyID, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeyService_GetKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKey'
type MockKeyService_GetKey_Call struct {
	*mock.Call
}

// GetKey is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID uuid.UUID
//   - scope model.Scope
func (_e *MockKeyService_Expecter) GetKey(ctx interface{}, keyID interface{}, scope interface{}) *MockKeyService_GetKey_Call {
	return &MockKeyService_GetKey_Call{Call: _e.mock.On("GetKey", ctx, keyID, scope)}
}

func (_c *MockKeyService_GetKey_Call) Run(run func(ctx context.Context, keyID uuid.UUID, scope model.Scope)) *MockKeyService_GetKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.Scope))
	})
	return _c
}

func (_c *MockKeyService_GetKey_Call) Return(_a0 *model.Key, _a1 error) *MockKeyService_GetKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeyService_GetKey_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.Scope) (*model.Key, error)) *MockKeyService_GetKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetKeyRotationPolicy provides a mock function with given fields: ctx, keyID, scope
func (_m *MockKeyService) GetKeyRotationPolicy(ctx context.Context, keyID uuid.UUID, scope model.Scope) (*model.KeyRotationPolicy, error) {
	ret := _m.Called(ctx, keyID, scope)

	if len(ret) == 0 {
		panic("no return value specified for GetKeyRotationPolicy")
	}

	var r0 *model.KeyRotationPolicy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) (*model.KeyRotationPolicy, error)); ok {
		return rf(ctx, keyID, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) *model.KeyRotationPolicy); ok {
		r0 = rf(ctx, keyID, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.KeyRotationPolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.Scope) error); ok {
		r1 = rf(ctx, keyID, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeyService_GetKeyRotationPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKeyRotationPolicy'
type MockKeyService_GetKeyRotationPolicy_Call struct {
	*mock.Call
}

// GetKeyRotationPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID uuid.UUID
//   - scope model.Scope
func (_e *MockKeyService_Expecter) GetKeyRotationPolicy(ctx interface{}, keyID interface{}, scope interface{}) *MockKeyService_GetKeyRotationPolicy_Call {
	return &MockKeyService_GetKeyRotationPolicy_Call{Call: _e.mock.On("GetKeyRotationPolicy", ctx, keyID, scope)}
}

func (_c *MockKeyService_GetKeyRotationPolicy_Call) Run(run func(ctx context.Context, keyID uuid.UUID, scope model.Scope)) *MockKeyService_GetKeyRotationPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.Scope))
	})
	return _c
}

func (_c *MockKeyService_GetKeyRotationPolicy_Call) Return(_a0 *model.KeyRotationPolicy, _a1 error) *MockKeyService_GetKeyRotationPolicy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeyService_GetKeyRotationPolicy_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.Scope) (*model.KeyRotationPolicy, error)) *MockKeyService_GetKeyRotationPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// GetKeyVersion provides a mock function with given fields: ctx, keyID, version, scope
func (_m *MockKeyService) GetKeyVersion(ctx context.Context, keyID uuid.UUID, version int, scope model.Scope) (*model.KeyVersion, error) {
	ret := _m.Called(ctx, keyID, version, scope)

	if len(ret) == 0 {
		panic("no return value specified for GetKeyVersion")
	}

	var r0 *model.KeyVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, model.Scope) (*model.KeyVersion, error)); ok {
		return rf(ctx, keyID, version, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, model.Scope) *model.KeyVersion); ok {
		r0 = rf(ctx, keyID, version, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.KeyVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, model.Scope) error); ok {
		r1 = rf(ctx, keyID, version, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeyService_GetKeyVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKeyVersion'
type MockKeyService_GetKeyVersion_Call struct {
	*mock.Call
}

// GetKeyVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID uuid.UUID
//   - version int
//   - scope model.Scope
func (_e *MockKeyService_Expecter) GetKeyVersion(ctx interface{}, keyID interface{}, version interface{}, scope interface{}) *MockKeyService_GetKeyVersion_Call {
	return &MockKeyService_GetKeyVersion_Call{Call: _e.mock.On("GetKeyVersion", ctx, keyID, version, scope)}
}

func (_c *MockKeyService_GetKeyVersion_Call) Run(run func(ctx context.Context, keyID uuid.UUID, version int, scope model.Scope)) *MockKeyService_GetKeyVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(model.Scope))
	})
	return _c
}

func (_c *MockKeyService_GetKeyVersion_Call) Return(_a0 *model.KeyVersion, _a1 error) *MockKeyService_GetKeyVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeyService_GetKeyVersion_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, model.Scope) (*model.KeyVersion, error)) *MockKeyService_GetKeyVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetPublicJWK provides a mock function with given fields: ctx, keyID, version, scope
func (_m *MockKeyService) GetPublicJWK(ctx context.Context, keyID uuid.UUID, version int, scope model.Scope) (*model.PublicJWK, error) {
	ret := _m.Called(ctx, keyID, version, scope)

	if len(ret) == 0 {
		panic("no return value specified for GetPublicJWK")
	}

	var r0 *model.PublicJWK
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, model.Scope) (*model.PublicJWK, error)); ok {
		return rf(ctx, keyID, version, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, model.Scope) *model.PublicJWK); ok {
		r0 = rf(ctx, keyID, version, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PublicJWK)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, model.Scope) error); ok {
		r1 = rf(ctx, keyID, version, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeyService_GetPublicJWK_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublicJWK'
type MockKeyService_GetPublicJWK_Call struct {
	*mock.Call
}

// GetPublicJWK is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID uuid.UUID
//   - version int
//   - scope model.Scope
func (_e *MockKeyService_Expecter) GetPublicJWK(ctx interface{}, keyID interface{}, version interface{}, scope interface{}) *MockKeyService_GetPublicJWK_Call {
	return &MockKeyService_GetPublicJWK_Call{Call: _e.mock.On("GetPublicJWK", ctx, keyID, version, scope)}
}

func (_c *MockKeyService_GetPublicJWK_Call) Run(run func(ctx context.Context, keyID uuid.UUID, version int, scope model.Scope)) *MockKeyService_GetPublicJWK_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(model.Scope))
	})
	return _c
}

func (_c *MockKeyService_GetPublicJWK_Call) Return(_a0 *model.PublicJWK, _a1 error) *MockKeyService_GetPublicJWK_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeyService_GetPublicJWK_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, model.Scope) (*model.PublicJWK, error)) *MockKeyService_GetPublicJWK_Call {
	_c.Call.Return(run)
	return _c
}

// ImportKey provides a mock function with given fields: ctx, req
func (_m *MockKeyService) ImportKey(ctx context.Context, req keys.ImportKeyRequest) (*keys.CreateKeyResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ImportKey")
	}

	var r0 *keys.CreateKeyResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, keys.ImportKeyRequest) (*keys.CreateKeyResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, keys.ImportKeyRequest) *keys.CreateKeyResult); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keys.CreateKeyResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, keys.ImportKeyRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeyService_ImportKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImportKey'
type MockKeyService_ImportKey_Call struct {
	*mock.Call
}

// ImportKey is a helper method to define mock.On call
//   - ctx context.Context
//   - req keys.ImportKeyRequest
func (_e *MockKeyService_Expecter) ImportKey(ctx interface{}, req interface{}) *MockKeyService_ImportKey_Call {
	return &MockKeyService_ImportKey_Call{Call: _e.mock.On("ImportKey", ctx, req)}
}

func (_c *MockKeyService_ImportKey_Call) Run(run func(ctx context.Context, req keys.ImportKeyRequest)) *MockKeyService_ImportKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(keys.ImportKeyRequest))
	})
	return _c
}

func (_c *MockKeyService_ImportKey_Call) Return(_a0 *keys.CreateKeyResult, _a1 error) *MockKeyService_ImportKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeyService_ImportKey_Call) RunAndReturn(run func(context.Context, keys.ImportKeyRequest) (*keys.CreateKeyResult, error)) *MockKeyService_ImportKey_Call {
	_c.Call.Return(run)
	return _c
}

// ListDeletedKeys provides a mock function with given fields: ctx, scope
func (_m *MockKeyService) ListDeletedKeys(ctx context.Context, scope model.Scope) ([]model.Key, error) {
	ret := _m.Called(ctx, scope)

	if len(ret) == 0 {
		panic("no return value specified for ListDeletedKeys")
	}

	var r0 []model.Key
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Scope) ([]model.Key, error)); ok {
		return rf(ctx, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Scope) []model.Key); ok {
		r0 = rf(ctx, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Key)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Scope) error); ok {
		r1 = rf(ctx, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeyService_ListDeletedKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDeletedKeys'
type MockKeyService_ListDeletedKeys_Call struct {
	*mock.Call
}

// ListDeletedKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - scope model.Scope
func (_e *MockKeyService_Expecter) ListDeletedKeys(ctx interface{}, scope interface{}) *MockKeyService_ListDeletedKeys_Call {
	return &MockKeyService_ListDeletedKeys_Call{Call: _e.mock.On("ListDeletedKeys", ctx, scope)}
}

func (_c *MockKeyService_ListDeletedKeys_Call) Run(run func(ctx context.Context, scope model.Scope)) *MockKeyService_ListDeletedKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Scope))
	})
	return _c
}

func (_c *MockKeyService_ListDeletedKeys_Call) Return(_a0 []model.Key, _a1 error) *MockKeyService_ListDeletedKeys_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeyService_ListDeletedKeys_Call) RunAndReturn(run func(context.Context, model.Scope) ([]model.Key, error)) *MockKeyService_ListDeletedKeys_Call {
	_c.Call.Return(run)
	return _c
}

// ListDueKeyRotationPolicies provides a mock function with given fields: ctx, scope
func (_m *MockKeyService) ListDueKeyRotationPolicies(ctx context.Context, scope model.Scope) ([]model.KeyRotationPolicy, error) {
	ret := _m.Called(ctx, scope)

	if len(ret) == 0 {
		panic("no return value specified for ListDueKeyRotationPolicies")
	}

	var r0 []model.KeyRotationPolicy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Scope) ([]model.KeyRotationPolicy, error)); ok {
		return rf(ctx, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Scope) []model.KeyRotationPolicy); ok {
		r0 = rf(ctx, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.KeyRotationPolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Scope) error); ok {
		r1 = rf(ctx, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeyService_ListDueKeyRotationPolicies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDueKeyRotationPolicies'
type MockKeyService_ListDueKeyRotationPolicies_Call struct {
	*mock.Call
}

// ListDueKeyRotationPolicies is a helper method to define mock.On call
//   - ctx context.Context
//   - scope model.Scope
func (_e *MockKeyService_Expecter) ListDueKeyRotationPolicies(ctx interface{}, scope interface{}) *MockKeyService_ListDueKeyRotationPolicies_Call {
	return &MockKeyService_ListDueKeyRotationPolicies_Call{Call: _e.mock.On("ListDueKeyRotationPolicies", ctx, scope)}
}

func (_c *MockKeyService_ListDueKeyRotationPolicies_Call) Run(run func(ctx context.Context, scope model.Scope)) *MockKeyService_ListDueKeyRotationPolicies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Scope))
	})
	return _c
}

func (_c *MockKeyService_ListDueKeyRotationPolicies_Call) Return(_a0 []model.KeyRotationPolicy, _a1 error) *MockKeyService_ListDueKeyRotationPolicies_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeyService_ListDueKeyRotationPolicies_Call) RunAndReturn(run func(context.Context, model.Scope) ([]model.KeyRotationPolicy, error)) *MockKeyService_ListDueKeyRotationPolicies_Call {
	_c.Call.Return(run)
	return _c
}

// ListKeyRotationPolicies provides a mock function with given fields: ctx, scope
func (_m *MockKeyService) ListKeyRotationPolicies(ctx context.Context, scope model.Scope) ([]model.KeyRotationPolicyWithKeyName, error) {
	ret := _m.Called(ctx, scope)

	if len(ret) == 0 {
		panic("no return value specified for ListKeyRotationPolicies")
	}

	var r0 []model.KeyRotationPolicyWithKeyName
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Scope) ([]model.KeyRotationPolicyWithKeyName, error)); ok {
		return rf(ctx, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Scope) []model.KeyRotationPolicyWithKeyName); ok {
		r0 = rf(ctx, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.KeyRotationPolicyWithKeyName)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Scope) error); ok {
		r1 = rf(ctx, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeyService_ListKeyRotationPolicies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListKeyRotationPolicies'
type MockKeyService_ListKeyRotationPolicies_Call struct {
	*mock.Call
}

// ListKeyRotationPolicies is a helper method to define mock.On call
//   - ctx context.Context
//   - scope model.Scope
func (_e *MockKeyService_Expecter) ListKeyRotationPolicies(ctx interface{}, scope interface{}) *MockKeyService_ListKeyRotationPolicies_Call {
	return &MockKeyService_ListKeyRotationPolicies_Call{Call: _e.mock.On("ListKeyRotationPolicies", ctx, scope)}
}

func (_c *MockKeyService_ListKeyRotationPolicies_Call) Run(run func(ctx context.Context, scope model.Scope)) *MockKeyService_ListKeyRotationPolicies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Scope))
	})
	return _c
}

func (_c *MockKeyService_ListKeyRotationPolicies_Call) Return(_a0 []model.KeyRotationPolicyWithKeyName, _a1 error) *MockKeyService_ListKeyRotationPolicies_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeyService_ListKeyRotationPolicies_Call) RunAndReturn(run func(context.Context, model.Scope) ([]model.KeyRotationPolicyWithKeyName, error)) *MockKeyService_ListKeyRotationPolicies_Call {
	_c.Call.Return(run)
	return _c
}

// ListKeyVersions provides a mock function with given fields: ctx, keyID, scope
func (_m *MockKeyService) ListKeyVersions(ctx context.Context, keyID uuid.UUID, scope model.Scope) ([]model.KeyVersion, error) {
	ret := _m.Called(ctx, keyID, scope)

	if len(ret) == 0 {
		panic("no return value specified for ListKeyVersions")
	}

	var r0 []model.KeyVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) ([]model.KeyVersion, error)); ok {
		return rf(ctx, keyID, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) []model.KeyVersion); ok {
		r0 = rf(ctx, keyID, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.KeyVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.Scope) error); ok {
		r1 = rf(ctx, keyID, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeyService_ListKeyVersions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListKeyVersions'
type MockKeyService_ListKeyVersions_Call struct {
	*mock.Call
}

// ListKeyVersions is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID uuid.UUID
//   - scope model.Scope
func (_e *MockKeyService_Expecter) ListKeyVersions(ctx interface{}, keyID interface{}, scope interface{}) *MockKeyService_ListKeyVersions_Call {
	return &MockKeyService_ListKeyVersions_Call{Call: _e.mock.On("ListKeyVersions", ctx, keyID, scope)}
}

func (_c *MockKeyService_ListKeyVersions_Call) Run(run func(ctx context.Context, keyID uuid.UUID, scope model.Scope)) *MockKeyService_ListKeyVersions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.Scope))
	})
	return _c
}

func (_c *MockKeyService_ListKeyVersions_Call) Return(_a0 []model.KeyVersion, _a1 error) *MockKeyService_ListKeyVersions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeyService_ListKeyVersions_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.Scope) ([]model.KeyVersion, error)) *MockKeyService_ListKeyVersions_Call {
	_c.Call.Return(run)
	return _c
}

// ListKeys provides a mock function with given fields: ctx, scope, filter
func (_m *MockKeyService) ListKeys(ctx context.Context, scope model.Scope, filter model.KeyFilter) ([]model.Key, error) {
	ret := _m.Called(ctx, scope, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListKeys")
	}

	var r0 []model.Key
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Scope, model.KeyFilter) ([]model.Key, error)); ok {
		return rf(ctx, scope, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Scope, model.KeyFilter) []model.Key); ok {
		r0 = rf(ctx, scope, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Key)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Scope, model.KeyFilter) error); ok {
		r1 = rf(ctx, scope, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeyService_ListKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListKeys'
type MockKeyService_ListKeys_Call struct {
	*mock.Call
}

// ListKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - scope model.Scope
//   - filter model.KeyFilter
func (_e *MockKeyService_Expecter) ListKeys(ctx interface{}, scope interface{}, filter interface{}) *MockKeyService_ListKeys_Call {
	return &MockKeyService_ListKeys_Call{Call: _e.mock.On("ListKeys", ctx, scope, filter)}
}

func (_c *MockKeyService_ListKeys_Call) Run(run func(ctx context.Context, scope model.Scope, filter model.KeyFilter)) *MockKeyService_ListKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Scope), args[2].(model.KeyFilter))
	})
	return _c
}

func (_c *MockKeyService_ListKeys_Call) Return(_a0 []model.Key, _a1 error) *MockKeyService_ListKeys_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeyService_ListKeys_Call) RunAndReturn(run func(context.Context, model.Scope, model.KeyFilter) ([]model.Key, error)) *MockKeyService_ListKeys_Call {
	_c.Call.Return(run)
	return _c
}

// PurgeKey provides a mock function with given fields: ctx, keyID, scope
func (_m *MockKeyService) PurgeKey(ctx context.Context, keyID uuid.UUID, scope model.Scope) error {
	ret := _m.Called(ctx, keyID, scope)

	if len(ret) == 0 {
		panic("no return value specified for PurgeKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) error); ok {
		r0 = rf(ctx, keyID, scope)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKeyService_PurgeKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurgeKey'
type MockKeyService_PurgeKey_Call struct {
	*mock.Call
}

// PurgeKey is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID uuid.UUID
//   - scope model.Scope
func (_e *MockKeyService_Expecter) PurgeKey(ctx interface{}, keyID interface{}, scope interface{}) *MockKeyService_PurgeKey_Call {
	return &MockKeyService_PurgeKey_Call{Call: _e.mock.On("PurgeKey", ctx, keyID, scope)}
}

func (_c *MockKeyService_PurgeKey_Call) Run(run func(ctx context.Context, keyID uuid.UUID, scope model.Scope)) *MockKeyService_PurgeKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.Scope))
	})
	return _c
}

func (_c *MockKeyService_PurgeKey_Call) Return(_a0 error) *MockKeyService_PurgeKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKeyService_PurgeKey_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.Scope) error) *MockKeyService_PurgeKey_Call {
	_c.Call.Return(run)
	return _c
}

// RecoverKey provides a mock function with given fields: ctx, keyID, scope
func (_m *MockKeyService) RecoverKey(ctx context.Context, keyID uuid.UUID, scope model.Scope) error {
	ret := _m.Called(ctx, keyID, scope)

	if len(ret) == 0 {
		panic("no return value specified for RecoverKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) error); ok {
		r0 = rf(ctx, keyID, scope)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKeyService_RecoverKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecoverKey'
type MockKeyService_RecoverKey_Call struct {
	*mock.Call
}

// RecoverKey is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID uuid.UUID
//   - scope model.Scope
func (_e *MockKeyService_Expecter) RecoverKey(ctx interface{}, keyID interface{}, scope interface{}) *MockKeyService_RecoverKey_Call {
	return &MockKeyService_RecoverKey_Call{Call: _e.mock.On("RecoverKey", ctx, keyID, scope)}
}

func (_c *MockKeyService_RecoverKey_Call) Run(run func(ctx context.Context, keyID uuid.UUID, scope model.Scope)) *MockKeyService_RecoverKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.Scope))
	})
	return _c
}

func (_c *MockKeyService_RecoverKey_Call) Return(_a0 error) *MockKeyService_RecoverKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKeyService_RecoverKey_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.Scope) error) *MockKeyService_RecoverKey_Call {
	_c.Call.Return(run)
	return _c
}

// RotateKey provides a mock function with given fields: ctx, keyID, scope
func (_m *MockKeyService) RotateKey(ctx context.Context, keyID uuid.UUID, scope model.Scope) (*keys.CreateKeyResult, error) {
	ret := _m.Called(ctx, keyID, scope)

	if len(ret) == 0 {
		panic("no return value specified for RotateKey")
	}

	var r0 *keys.CreateKeyResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) (*keys.CreateKeyResult, error)); ok {
		return rf(ctx, keyID, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) *keys.CreateKeyResult); ok {
		r0 = rf(ctx, keyID, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keys.CreateKeyResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.Scope) error); ok {
		r1 = rf(ctx, keyID, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeyService_RotateKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RotateKey'
type MockKeyService_RotateKey_Call struct {
	*mock.Call
}

// RotateKey is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID uuid.UUID
//   - scope model.Scope
func (_e *MockKeyService_Expecter) RotateKey(ctx interface{}, keyID interface{}, scope interface{}) *MockKeyService_RotateKey_Call {
	return &MockKeyService_RotateKey_Call{Call: _e.mock.On("RotateKey", ctx, keyID, scope)}
}

func (_c *MockKeyService_RotateKey_Call) Run(run func(ctx context.Context, keyID uuid.UUID, scope model.Scope)) *MockKeyService_RotateKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.Scope))
	})
	return _c
}

func (_c *MockKeyService_RotateKey_Call) Return(_a0 *keys.CreateKeyResult, _a1 error) *MockKeyService_RotateKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeyService_RotateKey_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.Scope) (*keys.CreateKeyResult, error)) *MockKeyService_RotateKey_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateKey provides a mock function with given fields: ctx, req
func (_m *MockKeyService) UpdateKey(ctx context.Context, req keys.UpdateKeyRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, keys.UpdateKeyRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKeyService_UpdateKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateKey'
type MockKeyService_UpdateKey_Call struct {
	*mock.Call
}

// UpdateKey is a helper method to define mock.On call
//   - ctx context.Context
//   - req keys.UpdateKeyRequest
func (_e *MockKeyService_Expecter) UpdateKey(ctx interface{}, req interface{}) *MockKeyService_UpdateKey_Call {
	return &MockKeyService_UpdateKey_Call{Call: _e.mock.On("UpdateKey", ctx, req)}
}

func (_c *MockKeyService_UpdateKey_Call) Run(run func(ctx context.Context, req keys.UpdateKeyRequest)) *MockKeyService_UpdateKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(keys.UpdateKeyRequest))
	})
	return _c
}

func (_c *MockKeyService_UpdateKey_Call) Return(_a0 error) *MockKeyService_UpdateKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKeyService_UpdateKey_Call) RunAndReturn(run func(context.Context, keys.UpdateKeyRequest) error) *MockKeyService_UpdateKey_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertKeyRotationPolicy provides a mock function with given fields: ctx, keyID, scope, req
func (_m *MockKeyService) UpsertKeyRotationPolicy(ctx context.Context, keyID uuid.UUID, scope model.Scope, req model.UpsertKeyRotationPolicyRequest) (*model.KeyRotationPolicy, error) {
	ret := _m.Called(ctx, keyID, scope, req)

	if len(ret) == 0 {
		panic("no return value specified for UpsertKeyRotationPolicy")
	}

	var r0 *model.KeyRotationPolicy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope, model.UpsertKeyRotationPolicyRequest) (*model.KeyRotationPolicy, error)); ok {
		return rf(ctx, keyID, scope, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope, model.UpsertKeyRotationPolicyRequest) *model.KeyRotationPolicy); ok {
		r0 = rf(ctx, keyID, scope, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.KeyRotationPolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.Scope, model.UpsertKeyRotationPolicyRequest) error); ok {
		r1 = rf(ctx, keyID, scope, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeyService_UpsertKeyRotationPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertKeyRotationPolicy'
type MockKeyService_UpsertKeyRotationPolicy_Call struct {
	*mock.Call
}

// UpsertKeyRotationPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID uuid.UUID
//   - scope model.Scope
//   - req model.UpsertKeyRotationPolicyRequest
func (_e *MockKeyService_Expecter) UpsertKeyRotationPolicy(ctx interface{}, keyID interface{}, scope interface{}, req interface{}) *MockKeyService_UpsertKeyRotationPolicy_Call {
	return &MockKeyService_UpsertKeyRotationPolicy_Call{Call: _e.mock.On("UpsertKeyRotationPolicy", ctx, keyID, scope, req)}
}

func (_c *MockKeyService_UpsertKeyRotationPolicy_Call) Run(run func(ctx context.Context, keyID uuid.UUID, scope model.Scope, req model.UpsertKeyRotationPolicyRequest)) *MockKeyService_UpsertKeyRotationPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.Scope), args[3].(model.UpsertKeyRotationPolicyRequest))
	})
	return _c
}

func (_c *MockKeyService_UpsertKeyRotationPolicy_Call) Return(_a0 *model.KeyRotationPolicy, _a1 error) *MockKeyService_UpsertKeyRotationPolicy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeyService_UpsertKeyRotationPolicy_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.Scope, model.UpsertKeyRotationPolicyRequest) (*model.KeyRotationPolicy, error)) *MockKeyService_UpsertKeyRotationPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateKeyAccess provides a mock function with given fields: ctx, keyID, userID, role
func (_m *MockKeyService) ValidateKeyAccess(ctx context.Context, keyID uuid.UUID, userID uuid.UUID, role string) error {
	ret := _m.Called(ctx, keyID, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for ValidateKeyAccess")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r0 = rf(ctx, keyID, userID, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKeyService_ValidateKeyAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateKeyAccess'
type MockKeyService_ValidateKeyAccess_Call struct {
	*mock.Call
}

// ValidateKeyAccess is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID uuid.UUID
//   - userID uuid.UUID
//   - role string
func (_e *MockKeyService_Expecter) ValidateKeyAccess(ctx interface{}, keyID interface{}, userID interface{}, role interface{}) *MockKeyService_ValidateKeyAccess_Call {
	return &MockKeyService_ValidateKeyAccess_Call{Call: _e.mock.On("ValidateKeyAccess", ctx, keyID, userID, role)}
}

func (_c *MockKeyService_ValidateKeyAccess_Call) Run(run func(ctx context.Context, keyID uuid.UUID, userID uuid.UUID, role string)) *MockKeyService_ValidateKeyAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *MockKeyService_ValidateKeyAccess_Call) Return(_a0 error) *MockKeyService_ValidateKeyAccess_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKeyService_ValidateKeyAccess_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string) error) *MockKeyService_ValidateKeyAccess_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockKeyService creates a new instance of MockKeyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKeyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKeyService {
	mock := &MockKeyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
