// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	certificates "rocketvault/internal/services/certificates"

	mock "github.com/stretchr/testify/mock"

	model "rocketvault/model"

	uuid "github.com/google/uuid"
)

// MockCertificateService is an autogenerated mock type for the CertificateService type
type MockCertificateService struct {
	mock.Mock
}

type MockCertificateService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCertificateService) EXPECT() *MockCertificateService_Expecter {
	return &MockCertificateService_Expecter{mock: &_m.Mock}
}

// CreateCASignedCertificate provides a mock function with given fields: ctx, req
func (_m *MockCertificateService) CreateCASignedCertificate(ctx context.Context, req certificates.CreateCertificateRequest) (*certificates.CreateCertificateResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateCASignedCertificate")
	}

	var r0 *certificates.CreateCertificateResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, certificates.CreateCertificateRequest) (*certificates.CreateCertificateResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, certificates.CreateCertificateRequest) *certificates.CreateCertificateResult); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*certificates.CreateCertificateResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, certificates.CreateCertificateRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCertificateService_CreateCASignedCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCASignedCertificate'
type MockCertificateService_CreateCASignedCertificate_Call struct {
	*mock.Call
}

// CreateCASignedCertificate is a helper method to define mock.On call
//   - ctx context.Context
//   - req certificates.CreateCertificateRequest
func (_e *MockCertificateService_Expecter) CreateCASignedCertificate(ctx interface{}, req interface{}) *MockCertificateService_CreateCASignedCertificate_Call {
	return &MockCertificateService_CreateCASignedCertificate_Call{Call: _e.mock.On("CreateCASignedCertificate", ctx, req)}
}

func (_c *MockCertificateService_CreateCASignedCertificate_Call) Run(run func(ctx context.Context, req certificates.CreateCertificateRequest)) *MockCertificateService_CreateCASignedCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(certificates.CreateCertificateRequest))
	})
	return _c
}

func (_c *MockCertificateService_CreateCASignedCertificate_Call) Return(_a0 *certificates.CreateCertificateResult, _a1 error) *MockCertificateService_CreateCASignedCertificate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCertificateService_CreateCASignedCertificate_Call) RunAndReturn(run func(context.Context, certificates.CreateCertificateRequest) (*certificates.CreateCertificateResult, error)) *MockCertificateService_CreateCASignedCertificate_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSelfSignedCertificate provides a mock function with given fields: ctx, req
func (_m *MockCertificateService) CreateSelfSignedCertificate(ctx context.Context, req certificates.CreateCertificateRequest) (*certificates.CreateCertificateResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateSelfSignedCertificate")
	}

	var r0 *certificates.CreateCertificateResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, certificates.CreateCertificateRequest) (*certificates.CreateCertificateResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, certificates.CreateCertificateRequest) *certificates.CreateCertificateResult); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*certificates.CreateCertificateResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, certificates.CreateCertificateRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCertificateService_CreateSelfSignedCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSelfSignedCertificate'
type MockCertificateService_CreateSelfSignedCertificate_Call struct {
	*mock.Call
}

// CreateSelfSignedCertificate is a helper method to define mock.On call
//   - ctx context.Context
//   - req certificates.CreateCertificateRequest
func (_e *MockCertificateService_Expecter) CreateSelfSignedCertificate(ctx interface{}, req interface{}) *MockCertificateService_CreateSelfSignedCertificate_Call {
	return &MockCertificateService_CreateSelfSignedCertificate_Call{Call: _e.mock.On("CreateSelfSignedCertificate", ctx, req)}
}

func (_c *MockCertificateService_CreateSelfSignedCertificate_Call) Run(run func(ctx context.Context, req certificates.CreateCertificateRequest)) *MockCertificateService_CreateSelfSignedCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(certificates.CreateCertificateRequest))
	})
	return _c
}

func (_c *MockCertificateService_CreateSelfSignedCertificate_Call) Return(_a0 *certificates.CreateCertificateResult, _a1 error) *MockCertificateService_CreateSelfSignedCertificate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCertificateService_CreateSelfSignedCertificate_Call) RunAndReturn(run func(context.Context, certificates.CreateCertificateRequest) (*certificates.CreateCertificateResult, error)) *MockCertificateService_CreateSelfSignedCertificate_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCertificate provides a mock function with given fields: ctx, certID, scope
func (_m *MockCertificateService) DeleteCertificate(ctx context.Context, certID uuid.UUID, scope model.Scope) error {
	ret := _m.Called(ctx, certID, scope)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCertificate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) error); ok {
		r0 = rf(ctx, certID, scope)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCertificateService_DeleteCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCertificate'
type MockCertificateService_DeleteCertificate_Call struct {
	*mock.Call
}

// DeleteCertificate is a helper method to define mock.On call
//   - ctx context.Context
//   - certID uuid.UUID
//   - scope model.Scope
func (_e *MockCertificateService_Expecter) DeleteCertificate(ctx interface{}, certID interface{}, scope interface{}) *MockCertificateService_DeleteCertificate_Call {
	return &MockCertificateService_DeleteCertificate_Call{Call: _e.mock.On("DeleteCertificate", ctx, certID, scope)}
}

func (_c *MockCertificateService_DeleteCertificate_Call) Run(run func(ctx context.Context, certID uuid.UUID, scope model.Scope)) *MockCertificateService_DeleteCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.Scope))
	})
	return _c
}

func (_c *MockCertificateService_DeleteCertificate_Call) Return(_a0 error) *MockCertificateService_DeleteCertificate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCertificateService_DeleteCertificate_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.Scope) error) *MockCertificateService_DeleteCertificate_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCertificatePolicy provides a mock function with given fields: ctx, certID, scope
func (_m *MockCertificateService) DeleteCertificatePolicy(ctx context.Context, certID uuid.UUID, scope model.Scope) error {
	ret := _m.Called(ctx, certID, scope)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCertificatePolicy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) error); ok {
		r0 = rf(ctx, certID, scope)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCertificateService_DeleteCertificatePolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCertificatePolicy'
type MockCertificateService_DeleteCertificatePolicy_Call struct {
	*mock.Call
}

// DeleteCertificatePolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - certID uuid.UUID
//   - scope model.Scope
func (_e *MockCertificateService_Expecter) DeleteCertificatePolicy(ctx interface{}, certID interface{}, scope interface{}) *MockCertificateService_DeleteCertificatePolicy_Call {
	return &MockCertificateService_DeleteCertificatePolicy_Call{Call: _e.mock.On("DeleteCertificatePolicy", ctx, certID, scope)}
}

func (_c *MockCertificateService_DeleteCertificatePolicy_Call) Run(run func(ctx context.Context, certID uuid.UUID, scope model.Scope)) *MockCertificateService_DeleteCertificatePolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.Scope))
	})
	return _c
}

func (_c *MockCertificateService_DeleteCertificatePolicy_Call) Return(_a0 error) *MockCertificateService_DeleteCertificatePolicy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCertificateService_DeleteCertificatePolicy_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.Scope) error) *MockCertificateService_DeleteCertificatePolicy_Call {
	_c.Call.Return(run)
	return _c
}

// GetCertificate provides a mock function with given fields: ctx, certID, scope
func (_m *MockCertificateService) GetCertificate(ctx context.Context, certID uuid.UUID, scope model.Scope) (*model.Certificate, error) {
	ret := _m.Called(ctx, certID, scope)

	if len(ret) == 0 {
		panic("no return value specified for GetCertificate")
	}

	var r0 *model.Certificate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) (*model.Certificate, error)); ok {
		return rf(ctx, certID, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) *model.Certificate); ok {
		r0 = rf(ctx, certID, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Certificate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.Scope) error); ok {
		r1 = rf(ctx, certID, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCertificateService_GetCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCertificate'
type MockCertificateService_GetCertificate_Call struct {
	*mock.Call
}

// GetCertificate is a helper method to define mock.On call
//   - ctx context.Context
//   - certID uuid.UUID
//   - scope model.Scope
func (_e *MockCertificateService_Expecter) GetCertificate(ctx interface{}, certID interface{}, scope interface{}) *MockCertificateService_GetCertificate_Call {
	return &MockCertificateService_GetCertificate_Call{Call: _e.mock.On("GetCertificate", ctx, certID, scope)}
}

func (_c *MockCertificateService_GetCertificate_Call) Run(run func(ctx context.Context, certID uuid.UUID, scope model.Scope)) *MockCertificateService_GetCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.Scope))
	})
	return _c
}

func (_c *MockCertificateService_GetCertificate_Call) Return(_a0 *model.Certificate, _a1 error) *MockCertificateService_GetCertificate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCertificateService_GetCertificate_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.Scope) (*model.Certificate, error)) *MockCertificateService_GetCertificate_Call {
	_c.Call.Return(run)
	return _c
}

// GetCertificatePolicy provides a mock function with given fields: ctx, certID, scope
func (_m *MockCertificateService) GetCertificatePolicy(ctx context.Context, certID uuid.UUID, scope model.Scope) (*model.CertificatePolicy, error) {
	ret := _m.Called(ctx, certID, scope)

	if len(ret) == 0 {
		panic("no return value specified for GetCertificatePolicy")
	}

	var r0 *model.CertificatePolicy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) (*model.CertificatePolicy, error)); ok {
		return rf(ctx, certID, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) *model.CertificatePolicy); ok {
		r0 = rf(ctx, certID, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CertificatePolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.Scope) error); ok {
		r1 = rf(ctx, certID, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCertificateService_GetCertificatePolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCertificatePolicy'
type MockCertificateService_GetCertificatePolicy_Call struct {
	*mock.Call
}

// GetCertificatePolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - certID uuid.UUID
//   - scope model.Scope
func (_e *MockCertificateService_Expecter) GetCertificatePolicy(ctx interface{}, certID interface{}, scope interface{}) *MockCertificateService_GetCertificatePolicy_Call {
	return &MockCertificateService_GetCertificatePolicy_Call{Call: _e.mock.On("GetCertificatePolicy", ctx, certID, scope)}
}

func (_c *MockCertificateService_GetCertificatePolicy_Call) Run(run func(ctx context.Context, certID uuid.UUID, scope model.Scope)) *MockCertificateService_GetCertificatePolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.Scope))
	})
	return _c
}

func (_c *MockCertificateService_GetCertificatePolicy_Call) Return(_a0 *model.CertificatePolicy, _a1 error) *MockCertificateService_GetCertificatePolicy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCertificateService_GetCertificatePolicy_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.Scope) (*model.CertificatePolicy, error)) *MockCertificateService_GetCertificatePolicy_Call {
	_c.Call.Return(run)
	return _c
}

// GetCertificateVersion provides a mock function with given fields: ctx, certID, version, scope
func (_m *MockCertificateService) GetCertificateVersion(ctx context.Context, certID uuid.UUID, version int, scope model.Scope) (*model.CertificateVersion, error) {
	ret := _m.Called(ctx, certID, version, scope)

	if len(ret) == 0 {
		panic("no return value specified for GetCertificateVersion")
	}

	var r0 *model.CertificateVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, model.Scope) (*model.CertificateVersion, error)); ok {
		return rf(ctx, certID, version, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, model.Scope) *model.CertificateVersion); ok {
		r0 = rf(ctx, certID, version, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CertificateVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, model.Scope) error); ok {
		r1 = rf(ctx, certID, version, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCertificateService_GetCertificateVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCertificateVersion'
type MockCertificateService_GetCertificateVersion_Call struct {
	*mock.Call
}

// GetCertificateVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - certID uuid.UUID
//   - version int
//   - scope model.Scope
func (_e *MockCertificateService_Expecter) GetCertificateVersion(ctx interface{}, certID interface{}, version interface{}, scope interface{}) *MockCertificateService_GetCertificateVersion_Call {
	return &MockCertificateService_GetCertificateVersion_Call{Call: _e.mock.On("GetCertificateVersion", ctx, certID, version, scope)}
}

func (_c *MockCertificateService_GetCertificateVersion_Call) Run(run func(ctx context.Context, certID uuid.UUID, version int, scope model.Scope)) *MockCertificateService_GetCertificateVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(model.Scope))
	})
	return _c
}

func (_c *MockCertificateService_GetCertificateVersion_Call) Return(_a0 *model.CertificateVersion, _a1 error) *MockCertificateService_GetCertificateVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCertificateService_GetCertificateVersion_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, model.Scope) (*model.CertificateVersion, error)) *MockCertificateService_GetCertificateVersion_Call {
	_c.Call.Return(run)
	return _c
}

// ListCertificatePolicies provides a mock function with given fields: ctx, scope
func (_m *MockCertificateService) ListCertificatePolicies(ctx context.Context, scope model.Scope) ([]model.CertificatePolicyWithCertName, error) {
	ret := _m.Called(ctx, scope)

	if len(ret) == 0 {
		panic("no return value specified for ListCertificatePolicies")
	}

	var r0 []model.CertificatePolicyWithCertName
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Scope) ([]model.CertificatePolicyWithCertName, error)); ok {
		return rf(ctx, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Scope) []model.CertificatePolicyWithCertName); ok {
		r0 = rf(ctx, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CertificatePolicyWithCertName)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Scope) error); ok {
		r1 = rf(ctx, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCertificateService_ListCertificatePolicies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCertificatePolicies'
type MockCertificateService_ListCertificatePolicies_Call struct {
	*mock.Call
}

// ListCertificatePolicies is a helper method to define mock.On call
//   - ctx context.Context
//   - scope model.Scope
func (_e *MockCertificateService_Expecter) ListCertificatePolicies(ctx interface{}, scope interface{}) *MockCertificateService_ListCertificatePolicies_Call {
	return &MockCertificateService_ListCertificatePolicies_Call{Call: _e.mock.On("ListCertificatePolicies", ctx, scope)}
}

func (_c *MockCertificateService_ListCertificatePolicies_Call) Run(run func(ctx context.Context, scope model.Scope)) *MockCertificateService_ListCertificatePolicies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Scope))
	})
	return _c
}

func (_c *MockCertificateService_ListCertificatePolicies_Call) Return(_a0 []model.CertificatePolicyWithCertName, _a1 error) *MockCertificateService_ListCertificatePolicies_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCertificateService_ListCertificatePolicies_Call) RunAndReturn(run func(context.Context, model.Scope) ([]model.CertificatePolicyWithCertName, error)) *MockCertificateService_ListCertificatePolicies_Call {
	_c.Call.Return(run)
	return _c
}

// ListCertificateVersions provides a mock function with given fields: ctx, certID, scope
func (_m *MockCertificateService) ListCertificateVersions(ctx context.Context, certID uuid.UUID, scope model.Scope) ([]model.CertificateVersion, error) {
	ret := _m.Called(ctx, certID, scope)

	if len(ret) == 0 {
		panic("no return value specified for ListCertificateVersions")
	}

	var r0 []model.CertificateVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) ([]model.CertificateVersion, error)); ok {
		return rf(ctx, certID, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) []model.CertificateVersion); ok {
		r0 = rf(ctx, certID, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CertificateVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.Scope) error); ok {
		r1 = rf(ctx, certID, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCertificateService_ListCertificateVersions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCertificateVersions'
type MockCertificateService_ListCertificateVersions_Call struct {
	*mock.Call
}

// ListCertificateVersions is a helper method to define mock.On call
//   - ctx context.Context
//   - certID uuid.UUID
//   - scope model.Scope
func (_e *MockCertificateService_Expecter) ListCertificateVersions(ctx interface{}, certID interface{}, scope interface{}) *MockCertificateService_ListCertificateVersions_Call {
	return &MockCertificateService_ListCertificateVersions_Call{Call: _e.mock.On("ListCertificateVersions", ctx, certID, scope)}
}

func (_c *MockCertificateService_ListCertificateVersions_Call) Run(run func(ctx context.Context, certID uuid.UUID, scope model.Scope)) *MockCertificateService_ListCertificateVersions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.Scope))
	})
	return _c
}

func (_c *MockCertificateService_ListCertificateVersions_Call) Return(_a0 []model.CertificateVersion, _a1 error) *MockCertificateService_ListCertificateVersions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCertificateService_ListCertificateVersions_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.Scope) ([]model.CertificateVersion, error)) *MockCertificateService_ListCertificateVersions_Call {
	_c.Call.Return(run)
	return _c
}

// ListCertificates provides a mock function with given fields: ctx, scope, filter
func (_m *MockCertificateService) ListCertificates(ctx context.Context, scope model.Scope, filter model.CertificateFilter) ([]model.Certificate, error) {
	ret := _m.Called(ctx, scope, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListCertificates")
	}

	var r0 []model.Certificate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Scope, model.CertificateFilter) ([]model.Certificate, error)); ok {
		return rf(ctx, scope, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Scope, model.CertificateFilter) []model.Certificate); ok {
		r0 = rf(ctx, scope, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Certificate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Scope, model.CertificateFilter) error); ok {
		r1 = rf(ctx, scope, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCertificateService_ListCertificates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCertificates'
type MockCertificateService_ListCertificates_Call struct {
	*mock.Call
}

// ListCertificates is a helper method to define mock.On call
//   - ctx context.Context
//   - scope model.Scope
//   - filter model.CertificateFilter
func (_e *MockCertificateService_Expecter) ListCertificates(ctx interface{}, scope interface{}, filter interface{}) *MockCertificateService_ListCertificates_Call {
	return &MockCertificateService_ListCertificates_Call{Call: _e.mock.On("ListCertificates", ctx, scope, filter)}
}

func (_c *MockCertificateService_ListCertificates_Call) Run(run func(ctx context.Context, scope model.Scope, filter model.CertificateFilter)) *MockCertificateService_ListCertificates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Scope), args[2].(model.CertificateFilter))
	})
	return _c
}

func (_c *MockCertificateService_ListCertificates_Call) Return(_a0 []model.Certificate, _a1 error) *MockCertificateService_ListCertificates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCertificateService_ListCertificates_Call) RunAndReturn(run func(context.Context, model.Scope, model.CertificateFilter) ([]model.Certificate, error)) *MockCertificateService_ListCertificates_Call {
	_c.Call.Return(run)
	return _c
}

// ListCertificatesDueForRenewal provides a mock function with given fields: ctx, scope
func (_m *MockCertificateService) ListCertificatesDueForRenewal(ctx context.Context, scope model.Scope) ([]model.Certificate, error) {
	ret := _m.Called(ctx, scope)

	if len(ret) == 0 {
		panic("no return value specified for ListCertificatesDueForRenewal")
	}

	var r0 []model.Certificate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Scope) ([]model.Certificate, error)); ok {
		return rf(ctx, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Scope) []model.Certificate); ok {
		r0 = rf(ctx, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Certificate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Scope) error); ok {
		r1 = rf(ctx, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCertificateService_ListCertificatesDueForRenewal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCertificatesDueForRenewal'
type MockCertificateService_ListCertificatesDueForRenewal_Call struct {
	*mock.Call
}

// ListCertificatesDueForRenewal is a helper method to define mock.On call
//   - ctx context.Context
//   - scope model.Scope
func (_e *MockCertificateService_Expecter) ListCertificatesDueForRenewal(ctx interface{}, scope interface{}) *MockCertificateService_ListCertificatesDueForRenewal_Call {
	return &MockCertificateService_ListCertificatesDueForRenewal_Call{Call: _e.mock.On("ListCertificatesDueForRenewal", ctx, scope)}
}

func (_c *MockCertificateService_ListCertificatesDueForRenewal_Call) Run(run func(ctx context.Context, scope model.Scope)) *MockCertificateService_ListCertificatesDueForRenewal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Scope))
	})
	return _c
}

func (_c *MockCertificateService_ListCertificatesDueForRenewal_Call) Return(_a0 []model.Certificate, _a1 error) *MockCertificateService_ListCertificatesDueForRenewal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCertificateService_ListCertificatesDueForRenewal_Call) RunAndReturn(run func(context.Context, model.Scope) ([]model.Certificate, error)) *MockCertificateService_ListCertificatesDueForRenewal_Call {
	_c.Call.Return(run)
	return _c
}

// ListDeletedCertificates provides a mock function with given fields: ctx, scope
func (_m *MockCertificateService) ListDeletedCertificates(ctx context.Context, scope model.Scope) ([]model.Certificate, error) {
	ret := _m.Called(ctx, scope)

	if len(ret) == 0 {
		panic("no return value specified for ListDeletedCertificates")
	}

	var r0 []model.Certificate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Scope) ([]model.Certificate, error)); ok {
		return rf(ctx, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Scope) []model.Certificate); ok {
		r0 = rf(ctx, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Certificate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Scope) error); ok {
		r1 = rf(ctx, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCertificateService_ListDeletedCertificates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDeletedCertificates'
type MockCertificateService_ListDeletedCertificates_Call struct {
	*mock.Call
}

// ListDeletedCertificates is a helper method to define mock.On call
//   - ctx context.Context
//   - scope model.Scope
func (_e *MockCertificateService_Expecter) ListDeletedCertificates(ctx interface{}, scope interface{}) *MockCertificateService_ListDeletedCertificates_Call {
	return &MockCertificateService_ListDeletedCertificates_Call{Call: _e.mock.On("ListDeletedCertificates", ctx, scope)}
}

func (_c *MockCertificateService_ListDeletedCertificates_Call) Run(run func(ctx context.Context, scope model.Scope)) *MockCertificateService_ListDeletedCertificates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Scope))
	})
	return _c
}

func (_c *MockCertificateService_ListDeletedCertificates_Call) Return(_a0 []model.Certificate, _a1 error) *MockCertificateService_ListDeletedCertificates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCertificateService_ListDeletedCertificates_Call) RunAndReturn(run func(context.Context, model.Scope) ([]model.Certificate, error)) *MockCertificateService_ListDeletedCertificates_Call {
	_c.Call.Return(run)
	return _c
}

// PurgeCertificate provides a mock function with given fields: ctx, certID, scope
func (_m *MockCertificateService) PurgeCertificate(ctx context.Context, certID uuid.UUID, scope model.Scope) error {
	ret := _m.Called(ctx, certID, scope)

	if len(ret) == 0 {
		panic("no return value specified for PurgeCertificate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) error); ok {
		r0 = rf(ctx, certID, scope)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCertificateService_PurgeCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurgeCertificate'
type MockCertificateService_PurgeCertificate_Call struct {
	*mock.Call
}

// PurgeCertificate is a helper method to define mock.On call
//   - ctx context.Context
//   - certID uuid.UUID
//   - scope model.Scope
func (_e *MockCertificateService_Expecter) PurgeCertificate(ctx interface{}, certID interface{}, scope interface{}) *MockCertificateService_PurgeCertificate_Call {
	return &MockCertificateService_PurgeCertificate_Call{Call: _e.mock.On("PurgeCertificate", ctx, certID, scope)}
}

func (_c *MockCertificateService_PurgeCertificate_Call) Run(run func(ctx context.Context, certID uuid.UUID, scope model.Scope)) *MockCertificateService_PurgeCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.Scope))
	})
	return _c
}

func (_c *MockCertificateService_PurgeCertificate_Call) Return(_a0 error) *MockCertificateService_PurgeCertificate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCertificateService_PurgeCertificate_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.Scope) error) *MockCertificateService_PurgeCertificate_Call {
	_c.Call.Return(run)
	return _c
}

// RecoverCertificate provides a mock function with given fields: ctx, certID, scope
func (_m *MockCertificateService) RecoverCertificate(ctx context.Context, certID uuid.UUID, scope model.Scope) error {
	ret := _m.Called(ctx, certID, scope)

	if len(ret) == 0 {
		panic("no return value specified for RecoverCertificate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) error); ok {
		r0 = rf(ctx, certID, scope)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCertificateService_RecoverCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecoverCertificate'
type MockCertificateService_RecoverCertificate_Call struct {
	*mock.Call
}

// RecoverCertificate is a helper method to define mock.On call
//   - ctx context.Context
//   - certID uuid.UUID
//   - scope model.Scope
func (_e *MockCertificateService_Expecter) RecoverCertificate(ctx interface{}, certID interface{}, scope interface{}) *MockCertificateService_RecoverCertificate_Call {
	return &MockCertificateService_RecoverCertificate_Call{Call: _e.mock.On("RecoverCertificate", ctx, certID, scope)}
}

func (_c *MockCertificateService_RecoverCertificate_Call) Run(run func(ctx context.Context, certID uuid.UUID, scope model.Scope)) *MockCertificateService_RecoverCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.Scope))
	})
	return _c
}

func (_c *MockCertificateService_RecoverCertificate_Call) Return(_a0 error) *MockCertificateService_RecoverCertificate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCertificateService_RecoverCertificate_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.Scope) error) *MockCertificateService_RecoverCertificate_Call {
	_c.Call.Return(run)
	return _c
}

// RenewCertificate provides a mock function with given fields: ctx, certID, scope, validityDays
func (_m *MockCertificateService) RenewCertificate(ctx context.Context, certID uuid.UUID, scope model.Scope, validityDays int) (*certificates.CreateCertificateResult, error) {
	ret := _m.Called(ctx, certID, scope, validityDays)

	if len(ret) == 0 {
		panic("no return value specified for RenewCertificate")
	}

	var r0 *certificates.CreateCertificateResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope, int) (*certificates.CreateCertificateResult, error)); ok {
		return rf(ctx, certID, scope, validityDays)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope, int) *certificates.CreateCertificateResult); ok {
		r0 = rf(ctx, certID, scope, validityDays)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*certificates.CreateCertificateResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.Scope, int) error); ok {
		r1 = rf(ctx, certID, scope, validityDays)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCertificateService_RenewCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenewCertificate'
type MockCertificateService_RenewCertificate_Call struct {
	*mock.Call
}

// RenewCertificate is a helper method to define mock.On call
//   - ctx context.Context
//   - certID uuid.UUID
//   - scope model.Scope
//   - validityDays int
func (_e *MockCertificateService_Expecter) RenewCertificate(ctx interface{}, certID interface{}, scope interface{}, validityDays interface{}) *MockCertificateService_RenewCertificate_Call {
	return &MockCertificateService_RenewCertificate_Call{Call: _e.mock.On("RenewCertificate", ctx, certID, scope, validityDays)}
}

func (_c *MockCertificateService_RenewCertificate_Call) Run(run func(ctx context.Context, certID uuid.UUID, scope model.Scope, validityDays int)) *MockCertificateService_RenewCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.Scope), args[3].(int))
	})
	return _c
}

func (_c *MockCertificateService_RenewCertificate_Call) Return(_a0 *certificates.CreateCertificateResult, _a1 error) *MockCertificateService_RenewCertificate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCertificateService_RenewCertificate_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.Scope, int) (*certificates.CreateCertificateResult, error)) *MockCertificateService_RenewCertificate_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCertificate provides a mock function with given fields: ctx, req
func (_m *MockCertificateService) UpdateCertificate(ctx context.Context, req certificates.UpdateCertificateRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCertificate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, certificates.UpdateCertificateRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCertificateService_UpdateCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCertificate'
type MockCertificateService_UpdateCertificate_Call struct {
	*mock.Call
}

// UpdateCertificate is a helper method to define mock.On call
//   - ctx context.Context
//   - req certificates.UpdateCertificateRequest
func (_e *MockCertificateService_Expecter) UpdateCertificate(ctx interface{}, req interface{}) *MockCertificateService_UpdateCertificate_Call {
	return &MockCertificateService_UpdateCertificate_Call{Call: _e.mock.On("UpdateCertificate", ctx, req)}
}

func (_c *MockCertificateService_UpdateCertificate_Call) Run(run func(ctx context.Context, req certificates.UpdateCertificateRequest)) *MockCertificateService_UpdateCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(certificates.UpdateCertificateRequest))
	})
	return _c
}

func (_c *MockCertificateService_UpdateCertificate_Call) Return(_a0 error) *MockCertificateService_UpdateCertificate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCertificateService_UpdateCertificate_Call) RunAndReturn(run func(context.Context, certificates.UpdateCertificateRequest) error) *MockCertificateService_UpdateCertificate_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCertificateVersion provides a mock function with given fields: ctx, req
func (_m *MockCertificateService) UpdateCertificateVersion(ctx context.Context, req certificates.UpdateCertificateVersionRequest) (*model.CertificateVersion, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCertificateVersion")
	}

	var r0 *model.CertificateVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, certificates.UpdateCertificateVersionRequest) (*model.CertificateVersion, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, certificates.UpdateCertificateVersionRequest) *model.CertificateVersion); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CertificateVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, certificates.UpdateCertificateVersionRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCertificateService_UpdateCertificateVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCertificateVersion'
type MockCertificateService_UpdateCertificateVersion_Call struct {
	*mock.Call
}

// UpdateCertificateVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - req certificates.UpdateCertificateVersionRequest
func (_e *MockCertificateService_Expecter) UpdateCertificateVersion(ctx interface{}, req interface{}) *MockCertificateService_UpdateCertificateVersion_Call {
	return &MockCertificateService_UpdateCertificateVersion_Call{Call: _e.mock.On("UpdateCertificateVersion", ctx, req)}
}

func (_c *MockCertificateService_UpdateCertificateVersion_Call) Run(run func(ctx context.Context, req certificates.UpdateCertificateVersionRequest)) *MockCertificateService_UpdateCertificateVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(certificates.UpdateCertificateVersionRequest))
	})
	return _c
}

func (_c *MockCertificateService_UpdateCertificateVersion_Call) Return(_a0 *model.CertificateVersion, _a1 error) *MockCertificateService_UpdateCertificateVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCertificateService_UpdateCertificateVersion_Call) RunAndReturn(run func(context.Context, certificates.UpdateCertificateVersionRequest) (*model.CertificateVersion, error)) *MockCertificateService_UpdateCertificateVersion_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertCertificatePolicy provides a mock function with given fields: ctx, certID, scope, req
func (_m *MockCertificateService) UpsertCertificatePolicy(ctx context.Context, certID uuid.UUID, scope model.Scope, req model.UpsertCertificatePolicyRequest) (*model.CertificatePolicy, error) {
	ret := _m.Called(ctx, certID, scope, req)

	if len(ret) == 0 {
		panic("no return value specified for UpsertCertificatePolicy")
	}

	var r0 *model.CertificatePolicy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope, model.UpsertCertificatePolicyRequest) (*model.CertificatePolicy, error)); ok {
		return rf(ctx, certID, scope, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope, model.UpsertCertificatePolicyRequest) *model.CertificatePolicy); ok {
		r0 = rf(ctx, certID, scope, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CertificatePolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.Scope, model.UpsertCertificatePolicyRequest) error); ok {
		r1 = rf(ctx, certID, scope, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCertificateService_UpsertCertificatePolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertCertificatePolicy'
type MockCertificateService_UpsertCertificatePolicy_Call struct {
	*mock.Call
}

// UpsertCertificatePolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - certID uuid.UUID
//   - scope model.Scope
//   - req model.UpsertCertificatePolicyRequest
func (_e *MockCertificateService_Expecter) UpsertCertificatePolicy(ctx interface{}, certID interface{}, scope interface{}, req interface{}) *MockCertificateService_UpsertCertificatePolicy_Call {
	return &MockCertificateService_UpsertCertificatePolicy_Call{Call: _e.mock.On("UpsertCertificatePolicy", ctx, certID, scope, req)}
}

func (_c *MockCertificateService_UpsertCertificatePolicy_Call) Run(run func(ctx context.Context, certID uuid.UUID, scope model.Scope, req model.UpsertCertificatePolicyRequest)) *MockCertificateService_UpsertCertificatePolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.Scope), args[3].(model.UpsertCertificatePolicyRequest))
	})
	return _c
}

func (_c *MockCertificateService_UpsertCertificatePolicy_Call) Return(_a0 *model.CertificatePolicy, _a1 error) *MockCertificateService_UpsertCertificatePolicy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCertificateService_UpsertCertificatePolicy_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.Scope, model.UpsertCertificatePolicyRequest) (*model.CertificatePolicy, error)) *MockCertificateService_UpsertCertificatePolicy_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateCertificateAccess provides a mock function with given fields: ctx, certID, scope
func (_m *MockCertificateService) ValidateCertificateAccess(ctx context.Context, certID uuid.UUID, scope model.Scope) error {
	ret := _m.Called(ctx, certID, scope)

	if len(ret) == 0 {
		panic("no return value specified for ValidateCertificateAccess")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) error); ok {
		r0 = rf(ctx, certID, scope)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCertificateService_ValidateCertificateAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateCertificateAccess'
type MockCertificateService_ValidateCertificateAccess_Call struct {
	*mock.Call
}

// ValidateCertificateAccess is a helper method to define mock.On call
//   - ctx context.Context
//   - certID uuid.UUID
//   - scope model.Scope
func (_e *MockCertificateService_Expecter) ValidateCertificateAccess(ctx interface{}, certID interface{}, scope interface{}) *MockCertificateService_ValidateCertificateAccess_Call {
	return &MockCertificateService_ValidateCertificateAccess_Call{Call: _e.mock.On("ValidateCertificateAccess", ctx, certID, scope)}
}

func (_c *MockCertificateService_ValidateCertificateAccess_Call) Run(run func(ctx context.Context, certID uuid.UUID, scope model.Scope)) *MockCertificateService_ValidateCertificateAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.Scope))
	})
	return _c
}

func (_c *MockCertificateService_ValidateCertificateAccess_Call) Return(_a0 error) *MockCertificateService_ValidateCertificateAccess_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCertificateService_ValidateCertificateAccess_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.Scope) error) *MockCertificateService_ValidateCertificateAccess_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateKeyOwnership provides a mock function with given fields: ctx, keyID, scope
func (_m *MockCertificateService) ValidateKeyOwnership(ctx context.Context, keyID uuid.UUID, scope model.Scope) error {
	ret := _m.Called(ctx, keyID, scope)

	if len(ret) == 0 {
		panic("no return value specified for ValidateKeyOwnership")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) error); ok {
		r0 = rf(ctx, keyID, scope)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCertificateService_ValidateKeyOwnership_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateKeyOwnership'
type MockCertificateService_ValidateKeyOwnership_Call struct {
	*mock.Call
}

// ValidateKeyOwnership is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID uuid.UUID
//   - scope model.Scope
func (_e *MockCertificateService_Expecter) ValidateKeyOwnership(ctx interface{}, keyID interface{}, scope interface{}) *MockCertificateService_ValidateKeyOwnership_Call {
	return &MockCertificateService_ValidateKeyOwnership_Call{Call: _e.mock.On("ValidateKeyOwnership", ctx, keyID, scope)}
}

func (_c *MockCertificateService_ValidateKeyOwnership_Call) Run(run func(ctx context.Context, keyID uuid.UUID, scope model.Scope)) *MockCertificateService_ValidateKeyOwnership_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.Scope))
	})
	return _c
}

func (_c *MockCertificateService_ValidateKeyOwnership_Call) Return(_a0 error) *MockCertificateService_ValidateKeyOwnership_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCertificateService_ValidateKeyOwnership_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.Scope) error) *MockCertificateService_ValidateKeyOwnership_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCertificateService creates a new instance of MockCertificateService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCertificateService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCertificateService {
	mock := &MockCertificateService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
